### ISSUE TITLE
Add `uuid()` function

### ISSUE THREAD

**Issue by casey** [casey/just#1018]
This came up in #1011. @page-down, what is your use case for a `uuid()` function? Would it return the same thing every time in a given invocation, or would it return a new UUID every time? Would something that generated a hex string of a certain length be more or less useful, or is there a specific advantage to UUIDs?

**Comment by page-down** [comment]
It is true that this suggestion is somewhat limited and should not be restricted to uuid. To be more useful, this function should actually be a pseudo-random number, pseudo-random string generator. I suggest changing the title of this issue.

The usage scenario is to generate a unique identifier during this execution to be shared by all processes executed by recipes.

For UUIDs, there should be at least standard format, hex format output. And at least UUID v1, UUID v4 versions should be available.

Each execution should output a new value, and the user should save the value to a variable.

The UUID is proposed because this is the format with a uniform standard. In other cases, the random string length, whether it covers numbers, alphabets, symbols, can be decided by the user by parameters.

Justfile can be made more cross-platform portable if useful tool functions are added without making just bloated.

**Comment by runeimp** [comment]
This seems like an odd request to me and would be a rare use case. Something that should just be a call to a command line tool which is baked-in or easily added to any OS that `just` runs on. Or wait until `just` implements Python or something.

**Comment by page-down** [comment]
> Something that should just be a call to a command line tool which is baked-in or easily added to any OS that just runs on.

Just like the functions that are currently available, they can actually be done with external tools. And `just` is not possible to provide all the utils that are similar to the standard library in a programming language.

I think to evaluate whether a feature is worth adding, you should judge whether it is generic enough, or it can solve some cross-platform problems, or it can improve script performance by reduce the overhead of starting processes.

If this function can unify the generation of pseudo-random strings across different platforms, can help users write scripts in a concise and clear manner, and is executed very efficiently, then it is good.

One of the core aspects of `just` is to help users efficiently execute common commands consisting of various tools and software. `just` can't go out and implement various tools for users. It is endless.

**Comment by runeimp** [comment]
Yeah, I'm a little surprised there are so many functions in `just` now. Seems odd to my mind as there is (or was) a desire to eventually embed Python or some scripting language and would largely negate the need for most if not all of those functions. Though I imagine it was easy enough for @casey to add such functions, I'm sure they are well appreciated by many, and as patches on the road to an actual embedded scripting language I think it will be odd when the embedded language lands. But that's probably just me. I've never truly disliked any of @casey's choices. Just is a great app. Feel free to ignore me. In this case I'm more "thinking out loud" than protesting. 👼

**Comment by casey** [comment]
I always appreciate the feedback! You imagine correctly, functions are easy to add, don't have much of a maintenance or complexity burden, aside from having to mention them in the docs, and are nice to have for the people who need them. It's true that if `just` eventually has an embedded shell or scripting language, they'll be a bit weird, but that doesn't seem so bad.

I've always wanted to add an embedded shell or scripting language, but since that's probably a ways away, I wouldn't want to hold up other features in the meantime.

**Comment by casey** [comment]
Done a while ago in #1170!
