### ISSUE TITLE
Allow overriding variables from commandline after specifying recipe

### ISSUE THREAD

**Issue by kaimast** [casey/just#1034]
It seems I can run something like `just BUILDTYPE=release build` but not `just build BUILDTYPE=release`.

For the latter I get `error: Justfile does not contain recipe BUILDTYPE=release.`. I assume a recipe name cannot contain an equals sign so either order should be allowed imho.

**Comment by casey** [comment]
This could be allowed, but I'm not sure it would be a net benefit.

Recipe names cannot contain equal signs, but recipe arguments can. So `just build foo=bar` could be setting `foo` to `bar`, or it could be passing `foo=bar` as an argument to build.

Since recipe arguments can contain equal signs, the implementation would have to examine whether or not an argument could be an override by looking at whether the preceding recipe took arguments. This seems a bit weird to me. It's nice to know what is an override by looking at the command line.

Variable overrides are applied before running any recipe. If you could mix overrides and recipes on the command line, this would be less clear, i.e. `just foo a=b bar b=c`.

**Comment by kaimast** [comment]
That make sense.

I guess overriding variables is how one passes arguments to make targets, so I usually pass them after the target.

**Comment by casey** [comment]
Usually arguments are used to pass a value to a recipe, and overrides are used to set global values. I'm going to go ahead and close this, I think it could be done, but I think it would be complicated, and not necessarily worth it. Thanks for opening the issue though!
