### ISSUE TITLE
Shebang recipe just hangs on Windows 10

### ISSUE THREAD

**Issue by PurpleMyst** [casey/just#1047]
As per the title, when I do the following, nothing happens for several second and not even Ctrl-C does anything:
```
❯ cat justfile
foo:
    #!py
    print("hello, world")

❯ just -vvvvvvvvvvvvvvvvvvvvvvvvv foo
===> Running recipe `foo`...
#!py

print("hello, world")
```

I'm on the latest version of Windows 10 and willing to provide more info if necessary.

**Comment by casey** [comment]
Thanks for reporting this!

```
-vvvvvvvvvvvvvvvvvvvvvvvvv
```

😂 I love it. There should be some sort of extra verbosity level that gets unlocked when you use more then ten `-v` flags.

This will be tricky for me to debug, because I don't have a windows box handy.

Some questions:

1. What version of just are you using?
2. Do recipes without a shebang work?
3. Can you try to run a recipe using powershell? I'm not sure, but I think this will look something like:

```
foo:
  #!powershell.exe -c
  Write-Host "Foo!"
```

**Comment by PurpleMyst** [comment]
Here you go, the `set shell` is important as otherwise just tries to use sh:
```shell
❯ cat justfile
set shell := ["pwsh.exe", "-c"]

foo:
    echo foo

bar:
    #!powershell.exe
    Write-Host "Bar!"

baz:
    #!powershell.exe -c
    Write-Host "Baz!"

ham:
    #!py
    print("ham")

spam:
    #!py -c
    print("spam")


❯ just foo
echo foo
foo

❯ just bar
Bar!

❯ just baz
Baz!

❯ just spam
# hangs

❯ just ham
# hangs

❯ just --version
just 0.10.2
```

**Comment by casey** [comment]
Wow, very weird. I don't know if I can debug this, since I don't have a windows dev box, and tests like this are passing on CI, which runs on Windows. Hopefully someone has some insight. Since I have limited resources to debug Windows issues, it would be awesome if a Just user who used Windows wanted to volunteer to help debug.

**Comment by PurpleMyst** [comment]
I'd be willing to look into this. I'm on Windows, obviously, and I know Rust. Could you please give me a few pointers on where to look in the code base?

**Comment by casey** [comment]
I think the first question to answer is: Where is the code hanging? Check out `Recipe::run`, which is what executes a recipe. Shebangs recipes have different code paths from linewise recipes (so-called because they're executed one line at a time), so I assume it's something there. You could try adding some logging statements.

In fact, logging statements would be helpful as a permanent addition, so you could add logging statements that help you figure out what's going on, and then make a PR to add those to the codebase.

**Comment by casey** [comment]
And by the way, thank you for taking a look!

**Comment by PurpleMyst** [comment]
Thank you for the pointers! I'll have a look once I have a chance. I'm very busy lately, so it may take me a bit.

**Comment by casey** [comment]
You bet, and no worries at all!

**Comment by presidento** [comment]
I think maybe it is not a `just` issue. `py` is the Python launcher which can be used if you want to use different Pythons or just run the latest available.

See this `justfile`:

```
set shell := ["powershell.exe", "-c"]

works1:
    #!python
    print("IT WORKS")

works2:
    #!python.exe
    print("IT WORKS")

works3:
    #!python38
    print("IT WORKS")

works4:
    #!python38.exe
    print("IT WORKS")

works5:
    #!C:\Users\MFarkas\scoop\apps\python39\current\python.exe
    print("IT WORKS")

wrong-use:
    #!python -c
    print("Syntax error")

hangs1:
    #!py
    print("It hangs")

hangs2:
    #!py.exe
    print("It hangs")

hangs3:
    #!C:\Users\MFarkas\scoop\apps\python39\current\py.exe
    print("It hangs")

```

**Comment by casey** [comment]
Interesting! I'll close this issue, since it seems like it isn't `just`-specific. Is it possible that `py.exe` is printing something to stderr or stdout that's getting swallowed, like a prompt or something?

**Comment by presidento** [comment]
I do not know exactly the issue, but it works well using `python` instead of `py`, so I think it can be closed.

Interestingly this works:

```
set shell := ["powershell.exe", "-c"]

works:
    py -c "print('Hello')"
```

This also works:

```
set shell := ["py.exe", "-c"]

works:
    print('Hello')
```

But this hangs:

```
set shell := ["powershell.exe", "-c"]

hangs:
    #!py
    print("It hangs")
```
