### ISSUE TITLE
Cross-platform justfiles & default shell

### ISSUE THREAD

**Issue by michidk** [casey/just#1050]
I know that there is already #531 as well as #3 but I am more looking for a workaround to have this right now.

What I want to achieve is something like this:
```make
[conditional(os_family = "windows")]
set shell := ["powershell"]
```

Because 
```make
set shell := ["powershell"]
```
makes the file unusable for linux users that work on the same project.

I have hoped that one could use conditionals for that:
```make
shell := if os() == "windows" { "powershell" } else { "bash" }
```
But then I get the error: `...  because just could not find the shell: The system cannot find the file specified. (os error 2)`
Putting the `set` keyword at the beginning gives `Expected '[', but found identifier`

But even if that would work, I don't want to default to `bash` for Linux, so it would be nice if something like this was possible:
```make
shell := if os() == "windows" { "powershell" } else { shell }
```

I also tried the `--shell` flag with various arguments ("powershell", "powershell.exe", "["powershell"]") but couldn't get it to work.
This solution would be okay, since I then could set an alias on my system to always include that flag.

It would be even better if the default shell on Windows would just be "powershell".

**Comment by casey** [comment]
> It would be even better if the default shell on Windows would just be "powershell".

I think this makes a lot of sense.

Very early on, the way I got `just` working on Windows was to install cygwin, a unix userland (`sh` and utilities, like `cp`, `rm`, etc) for Windows. This worked well, and a lot of justfiles were sort of cross-platform, but required installing cygwin. Cygwin is pretty weird, and pretty esoteric. Most Windows users these days use WSL if they want a unix command line, and use powershell when they're in native Windows.

I think it makes sense to default to Powershell if it's the native Windows binary:

- Powershell *is* the system shell on Windows. For a windows user, it should be the default
- Powershell is installed on all modern Windows machines
- cmd.exe is unpopular and weird, so that's not a good option
- Powershell doesn't require any dependencies

Changing the default, however, would break a lot of existing justfiles. So, what I propose as a first step is to add a setting that changes the shell to powershell, but only if the os is windows.

Something like:

```
# use powershell on Windows instead of `sh`
set windows-powershell := true
```

This would allow writing cross-platform-ish Justfiles, as long as you stick to the shared subset of `powershell` and `sh`, and would also allow Windows users to get a good experience that doesn't require installing any dependencies.

If this was popular, we could then figure out a way to phase it in as a default, or at least make it more convenient, perhaps with something like Rust editions.

**Comment by casey** [comment]
Another thought: `set windows-powershell := true` could also try to do something smarter with positional arguments, so that you can use those with powershell. There was some issue here, I think because the positional arguments implementation passes the name of the recipe as the first argument, which is unused, and powershell doesn't like unused positional arguments.

**Comment by michidk** [comment]
I like the approach with `set windows-powershell := true`.
In the meantime can you please explain if and how its possible to use conditionals for that use?
From the docs it looks like `shell := if os() == "windows" { "powershell" } else { "bash" }` should work.

In my first post I mentioned that I couldn't get `--shell` to work. After a look into the code, I figured that the correct usage is:
`just --shell powershell.exe --shell-arg -c` which works fine.

It would be great if I could set those as environment variables so I don't have to repeat them everytime I use the command. I think this would be a simple workaround for that problem. I implemented this in https://github.com/casey/just/pull/1055.

**Comment by casey** [comment]
> In the meantime can you please explain if and how its possible to use conditionals for that use? From the docs it looks like `shell := if os() == "windows" { "powershell" } else { "bash" }` should work.

`shell := …` and `set shell := …` are not the same. The former sets a variable, the latter sets a setting.

It is not possible to use conditionals because the right hand side of `set shell` must be evaluated before anything else, so it can only contain a list of string literals.

> It would be great if I could set those as environment variables so I don't have to repeat them everytime I use the command. I think this would be a simple workaround for that problem. I implemented this in #1055.

I'm a bit torn on this. On the one hand, it is a simple workaround. On the other hand, `set windows-powershell` is about as simple to implement, and provides a much better solution to the problem. Do you want to try to implement `set windows-powershell`?

**Comment by michidk** [comment]
I am not sure it is quite as simple to implement, but I can give it a shot. I actually would be in favor of implementing both solutions. `windows-powershell` seems a bit limited because it only solves the problem for powershell users, while the environment variables provide a completely dynamic approach.

But (copying this statement of yours from my previous PR) it seems like this is technically not possible, because of some problem with recursion (are the env vars not kept for recursive invocations? shouldn't that be fixed then?):
> I've been thinking about this, and I don't actually think it's a good idea. Pulling the shell from environment variables will break recursive invocations of just which expect the default shell.

**Comment by casey** [comment]
> But (copying this statement of yours from my previous PR) it seems like this is technically not possible, because of some problem with recursion (are the env vars not kept for recursive invocations? shouldn't that be fixed then?):

It's actually the opposite problem: Environment variables are passed to child processes. So if set `JUST_SHELL` to `fish`, then, then call `just` with a justfile that expects `JUST_SHELL` to be set to `fish`, it will work, but then if inside that justfiel you invoke `just` again, but with a justfile that does not expect `JUST_SHELL` to be set to `fish` it will break.

**Comment by michidk** [comment]
Gotcha. 
I have started working on this feature: https://github.com/casey/just/pull/1057 (just parsing the setting for now & some docs)
Though I am not sure where to put the code that checks the settings and overrides the shell. Could you please point me to an appropriate location in the code?

I think it should still be possible to overwrite the `windows-powershell` behaviour with `--shell`.
To implement that, I was thinking about removing the default values for `SHELL` and `SHELL_ARGS` in the clap config. Later we could check if those values exist:
- if they exist: use the shell (& shell args) given by `SHELL`
- if not, check the OS `just` was compiled against:
  - if windows:
    - check if `windows-powershell` is set:
      - if true: overwrite shell with `powershell.exe` and shell args with `-c`
      - else: use bash
  - else: use bash

**Comment by casey** [comment]
> Gotcha. I have started working on this feature: #1057 (just parsing the setting for now & some docs) Though I am not sure where to put the code that checks the settings and overrides the shell. Could you please point me to an appropriate location in the code?

I believe that the shell ultimately comes from the `Settings` struct in `src/settings.rs`

> I think it should still be possible to overwrite the `windows-powershell` behaviour with `--shell`. To implement that, I was thinking about removing the default values for `SHELL` and `SHELL_ARGS` in the clap config.

That sounds right to me. `--shell` and `--shell-arg` can override the shell, `set windows-powershell` only changes the default shell on windows. I would remove the default values from `config.rs`

> Later we could check if those values exist:
> 
> * if they exist: use the shell (& shell args) given by `SHELL`
> * if not, check the OS `just` was compiled against:
>   
>   * if windows:
>     
>     * check if `windows-powershell` is set:
>       
>       * if true: overwrite shell with `powershell.exe` and shell args with `-c`
>       * else: use bash
>   * else: use bash

This is correct, although `just` uses `sh` by default, not `bash`.

**Comment by michidk** [comment]
While implementing this feature I noticed that most unit tests won't even run on Windows (at least without tools like cgywin), because they depend on tools from the Linux ecosystem. While I found some issues with `just` when using Powershell/Windows in general (#1061, #1060, #1062), it seems like mostly it would work (and I already used it that way). But rewriting around 500 tests to work on Windows is just out of the scope. I started going through each of them and annotating them with `#[cfg(unix)]` but even this is a lot of work and I probably won't finish that. So for now I would suggest always using Linux for running the tests and only having unit tests on Windows for specific Windows functionality.

**Comment by casey** [comment]
Yo! I don't have enough time to respond properly, but I want to save you from doing a ton of work. I'll respond at length when I get the chance, but this only needs one additional test that checks that adding `set windows-powershell := true` causes `just` to use `powershell` as the shell on windows. I don't think that any of the existing tests need to be modified.

**Comment by casey** [comment]
And happy New Year!

**Comment by alshdavid** [comment]
It would be nice to annotate recipes to allow for overloading them across platforms (when building native Windows binaries)

```yaml
build:
  rm -rf target
  cargo build

#[cfg(target_os = "windows")]
build:
  Remove-Item -Recurse -Force target
  cargo build
```

I achieved something similar with
```yaml
build:
  @just {{ if os() == "Windows_NT" { "build-windows" } else { "build-default" } }}

build-default:
  echo Nix

build-windows:
  echo Windows
```

**Comment by cfxegbert** [comment]
> It would be nice to annotate recipes to allow for overloading them across platforms (when building native Windows binaries)

This feature already exists as recipe attributes of [linux], [macos], [unix], and [windows]

**Comment by alshdavid** [comment]
wait, actually?

https://just.systems/man/en/chapter_32.html 🤦🤦🤦🤦🤦

**Comment by koppor** [comment]
> wait, actually?
> 
> [just.systems/man/en/chapter_32.html](https://just.systems/man/en/chapter_32.html) 🤦🤦🤦🤦🤦

Updated link: https://just.systems/man/en/attributes.html

(For the googlers finding this page first and not the manual page)

```just
[unix]
run:
  cc main.c
  ./a.out

[windows]
run:
  cl main.c
  main.exe
```
