### ISSUE TITLE
The latest release v0.10.6 is missing platform specific archives

### ISSUE THREAD

**Issue by mohi7solanki** [casey/just#1076]
My gitlab pipeline failed with the followring error while installing latest version
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
I guess this is because of missing archives ref https://github.com/casey/just/releases/tag/0.10.6 - Assets doesn't have any archives for macOS, windows etc
On macOS, the latest version installation fails with the following error
```
install: error: Could not determine target from output of `uname -m`-`uname -s`, please use `--target`: arm64-Darwin
```

**Comment by casey** [comment]
Thanks for reporting this! For some reason the tests in the release workflow are failing, but aren't failing in the CI workflow. I removed the tests in the release workflow, since they aren't really doing much (all tests run on every commit in the CI workflow) and am releasing 0.10.7 which will trigger a rebuild of the archives.

**Comment by mohi7solanki** [comment]
Thanks for the quick fix!
