### ISSUE TITLE
[feature request] Add syntax for declaring receipe dependency on 3rd party tool

### ISSUE THREAD

**Issue by eshepelyuk** [casey/just#1088]
Hello

`Just` recepies are often used to call other 3rd party tools, like compilers, formatters etc. If justfiles are used by multiple devs within the sam organization, those devs may not have the tools installed at their computers at the moment. Since missing tool errors may be quite cryptic during the execution - I propose to implement following

1. Come up with an idea of syntax to declare that justfile execution depends on some tool, e.g. `kubectl`.
2. Dependency may be declared either for entire justfile or for particular receipe, what is easier to implement.
3. Dependency declaration syntax may allow definition of custom error message.
4. Dependency declaration should allow definition of installation instruction link.

So if a person runs one of the recepies that requires `kubectl` to be installed - `just` will provide a clean message with direct installation link if that tool is missing from person's computer.
WDYT ?

**Comment by casey** [comment]
I definitely agree that this is a problem, however I don't think that it's possible for `just` to solve it in a general way. In particular:

- Dependencies can be installed in many different ways, not just by a link. Sometimes you need to run a command, sometimes you need to follow instructions that you can link to, sometimes you need to install something on an app store.
- There's no general way to detect if a command has failed because a dependency is missing.
- There's no general way to detect if a dependency is available.

**Comment by dionjwa** [comment]
I have solved this in a different way:

1. recipes can depend on a recipe that checks if in a docker container
2. if not in a docker container, fail and print command to enter the container (in my case, the default command immediately creates a docker container and mounts the local directory in)
3. When in the docker container, you completely control the environment

Here's a subset of a justfile with just those steps. It might not work, I didn't test it, but I copied it from a bigger one that works:

```justfile
set shell       := ["bash", "-c"]
set dotenv-load := true
export DOCKER_IMAGE_PREFIX         := env_var_or_default("DOCKER_IMAGE_PREFIX", "")
export DOCKER_TAG                  := env_var_or_default("DOCKER_TAG", `git rev-parse --short HEAD`)

_help:
    #!/usr/bin/env bash
    if [ -f /.dockerenv ]; then
        just --list --unsorted
    else
        # Not in a docker container? Get in one
        just _docker .
    fi

@some-other-command: _ensure_inside_docker
    echo "I am definitely in a docker container"

_ensure_inside_docker:
    #!/usr/bin/env bash
    if [ ! -f /.dockerenv ]; then
        echo -e "🌵🔥🌵🔥🌵🔥🌵 First run the command: just 🌵🔥🌵🔥🌵🔥🌵"
        exit 1
    fi

# Build and run the cloud image, used deployments
_docker +args="bash": _build
    #!/usr/bin/env bash
    # exit when any command fails
    set -euo pipefail
    mkdir -p .tmp
    touch .tmp/.bash_history
    docker run \
        $(if [ "$CI" != 'true' ]; then echo '-ti'; fi) \
        -e CI=true \
        -e PS1='<${PWD#"${PWD%/*/*}/"}/> ' \
        -e PROMPT="<%/% > " \
        -e DOCKER_IMAGE_PREFIX={{DOCKER_IMAGE_PREFIX}} \
        -e HISTFILE=.tmp/.bash_history \
        -v .:/app \
        {{DOCKER_IMAGE_PREFIX}}cloud:{{DOCKER_TAG}} {{args}}

# If the ./app docker image in not build, then build it
_build:
    #!/usr/bin/env bash
    set -euo pipefail
    # No buildkit, it does not use the local cache, which we want
    export DOCKER_BUILDKIT=0
    export DOCKER_PLATFORM="$(docker version -f '{{{{json .}}' | jq -r '.Server.Arch')"
    if [[ "$(docker images -q {{DOCKER_IMAGE_PREFIX}}cloud:{{DOCKER_TAG}} 2> /dev/null)" == "" ]]; then
        echo -e "🚪🚪  ➡ Building ./cloud docker image ... 🚪🚪 ";
        docker build -f Dockerfile -t {{DOCKER_IMAGE_PREFIX}}cloud:{{DOCKER_TAG}} . ;
    fi
```

It's really really convenient and simplifies development when you can guarantee and version the available tools in the CLI environment. For me, the only place that isn't dockerized is browser development, since that machinery is still too slow to run in a container efficiently (once the website is sufficiently complex). 

It also makes CI/CD easier, since all the pipeline tools can be versioned and controlled together, since everything is just containers.

**Comment by jenisys** [comment]
I came up with a similar solution than the one provided by @dionjwa .

```make
# -- FILE: justfile
# USECASE: Python -- Use "pip" to install Python packages.
HERE := justfile_directory()

# DEFAULT-TARGET: Run the tests.
default: test

# PART=all, testing, other, ...
install-packages PART="all":
    @echo "INSTALL-PACKAGES: {{PART}} ..."
    pip install --quiet -r py.requirements/{{PART}}.txt
    @touch "{{HERE}}/.done.install-packages.{{PART}}"

_ensure-install-packages PART="all":
    #!/usr/bin/env python3
    from subprocess import run
    from os import path
    if not path.exists("{{HERE}}/.done.install-packages.{{PART}}"):
        run("just install-packages {{PART}}", shell=True)

test *TESTS: (_ensure-install-packages "testing") 
    pytest {{TESTS}}

other-command: (_ensure-install-packages "other") 
    @echo "Run OTHER command ..."
    ...
```

A similar approach should work for package manager(s), like `apt`.
You just need a small script that reads the package list from a file.
And you can use other recipes, like `_ensure-install-apt-packages` and `install-apt-packages`, etc. (if multiple package managers are involved.

**Comment by PaulRBerg** [comment]
I've opened another issue for this feature request — what if Just could simply [look into $PATH to see if the dependencies are defined there](https://github.com/casey/just/issues/2755)?
