### ISSUE TITLE
Surprising that just doesn't enable -o pipefail by default

### ISSUE THREAD

**Issue by ansel1** [casey/just#1107]
The docs section "Safer Bash Shebang Recipes", you recommend using pipefail, and suggest that will replicate how just executes normal recipes.  But in testing, it doesn't seem like it does:

    shouldfail:
      which lss | cat

If pipefail were enabled, that should fail (since "lss" isn't found).  

Either docs should mention that pipefail *isn't* enabled by default, or consider enabling it.

**Comment by casey** [comment]
`just` calls `sh`, not `bash`, and `set -o pipefail` isn't supported by some of the shells that are commonly installed as `sh`, like dash, so `just` can't use it by default.

The current wording of the readme is unclear though, since it sounds like `set -o pipefail` is used in linewise recipes by default. I'll add something that clarifies that.
