### ISSUE TITLE
Can't run NVM in justfile

### ISSUE THREAD

**Issue by chav-aniket** [casey/just#1124]
Hiya just wondering if there's a reason I wouldn't be able to run nvm commands through justfile, not sure what details to put so I'll leave the most general one, OS: Win10 running WSL Ubuntu. Thanks!

**Comment by casey** [comment]
I'm not familiar with nvm, but looking at the readme, I think it's implemented as a shell function that manipulates local shell variables. Just invokes `sh`, which might not read the config file that defines that shell function. If it is defined, it still might not work, because just executes recipes line by line, and variables defined on one line aren't available on the next.

**Comment by chav-aniket** [comment]
I think that makes sense, I did expect nvm install to at least work if not nvm use. I don't know too much about the technicality for both nvm and just so I'm not so sure what a solution could even look like, thank you for having a look though!

**Comment by casey** [comment]
You're welcome! Sorry I don't have a good answer for you.
