### ISSUE TITLE
Readmy doesn't mention identation rules

### ISSUE THREAD

**Issue by twolodzko** [casey/just#1135]
Makefiles are pretty strict about indentation rules, `just`'s readme doesn't say anything about it. Does it use tabs-only or maybe any whitespaces are ok? Is it configurable?

**Comment by casey** [comment]
Good point!

Actually, I don't think anyone has ever asked what the indentation rules are, even though they're fairly complicated. Probably because they're pretty forgiving, and the error messages you get if you don't follow them are specific and informative.

Recipe lines may begin with any number of tabs or spaces, but not a mix of the two. All lines of a given recipe must use the same leading indentation, however different recipes may use different indentation.

I'll mention this in the readme.
