### ISSUE TITLE
Can't pass flags to just after slash invocation

### ISSUE THREAD

**Issue by anacrolix** [casey/just#1150]
```
$ just ~/ags/dht-indexer/sql/ -l
error: Justfile does not contain recipe `-l`.
$ just -f ~/ags/dht-indexer/sql/justfile -l
Available recipes:
    clone-index src_db new_db
    run-sqlite-script db script
$ just -l ~/ags/dht-indexer/sql/
Available recipes:
    clone-index src_db new_db
    run-sqlite-script db script

```

**Comment by casey** [comment]
This would definitely be nice to allow, but I don't think it's supported by the argument parser that we're using. Because it's common to want to pass flags as arguments to recipes, `just` stops parsing flags when it gets to the first positional argument, which can be a recipe name, path, or path and recipe name. It would be nice to continue parsing flags if the argument is a path without a recipe name, as in your example, but I don't think it's possible to get clap to do that.
