### ISSUE TITLE
add new line escapes

### ISSUE THREAD

**Issue by dm9pZCAq** [casey/just#1157]
here is Makefile
```Makefile
rule: many many \
    many many many requirements
%:
    @echo $@
```

it would be nice to have this also in Just

and some more examples
```Makefile
# this is Justfile
# for now ther is `error: Unknown start of token` at backslash

var := "a" \
       "b" \
       "c" \
       "d" \
       "e" \
       "f" \
       "..."

# or `if` inside rule
default:
   echo "hello, {{ \
     if "2" == "2" { \
       "long string so not Good!" \
     } else { \
       "it would be nice if i can split" \
       + " it to more lines 1984" \
     } \
   }}"
```

**Comment by casey** [comment]
For the `var` case you can use parenthesis:

```
var := (
  "a" + 
  "b"
)

For the other two cases line breaks would definitely be nice.

**Comment by dm9pZCAq** [comment]
then there also should be added spaces
```Makefile
var := (
  "a " + 
  "b " +
  "c " +
  "..."
)
```

**Comment by nk9** [comment]
For the record, a workaround for prerequisites is currently available by nesting them, e.g.:

```just
@compound: a b
    echo "compound"

@a: one two three

@b: four five six

@one:
    echo "one"

@two:
    echo "two"

@three:
    echo "three"

@four:
    echo "four"

@five:
    echo "five"

@six:
    echo "six"
```

```bash
$ just compound
one
two
three
four
five
six
compound
```

**Comment by nk9** [comment]
[Moved from the PR since it's already been merged.]

@casey, @laniakea64 has noticed that this works in a bunch of other cases. See https://github.com/nk9/just_sublime/issues/23 and this gist: https://gist.github.com/laniakea64/b3381389beca11226cb8fefc4e1abf85

Just wanted to check: is this intentional/desired? If it is, there should probably be a lot more tests.

I should note that things like allowing an escaped newline between `set` and the setting name, or between the variable name and the assignment operator, will thoroughly break the existing syntaxes. Not clear to me that there's a compelling reason to allow escaping newlines this broadly.

**Comment by casey** [comment]
I think this is as expected. Only allowing `\` in certain contexts would force processing it in the parser, instead of the lexer, which would be a weirder and more complicated implementation. I'm not sure if more tests are necessary though, since afaict, those different contexts that a `\` can appear in don't exercise different code paths in the implementation.

**Comment by ids1024** [comment]
I think languages that allow newline escaping like this (which is pretty common) generally do so at a lexing level like this, so you can have an escaped newline anywhere a space can be.  That's the behavior I'd expect.

It's useful in various contexts. And it's not a problem if it's allowed in places where it seems unusual to use. But if there are any specific behaviors that seem buggy, that's something to address.
