### ISSUE TITLE
just without parameters runs first command in justfile

### ISSUE THREAD

**Issue by epogrebnyak** [casey/just#1166]
I'm back to exporing `just` for more projects and think the command runner is great, allows iterating very quickly in the project, very useful to me.

Ignore if this was discussed before, here is what I noticed: simply `just` will run the first command in justfile. I saw that on Windows before, but now I see in it Linux as well. Maybe the behaviour should be showing `just --help` or `just --list`? Running first command is a bit unpredictable.

**Comment by casey** [comment]
I think this has been talked about before, but discussion is always welcome. This mirrors `make`, which will run the first recipe in the `Makefile` if you type `make` without any arguments.

I usually set the first command to something safe and useful, like building the program, or running tests. If there's no safe and useful recipe, I'll do something like this:

```
default:
  just --list
```

So that if you don't supply any arguments, it just prints available recipes.

**Comment by nk9** [comment]
FWIW, I like the current behavior.

**Comment by casey** [comment]
The current behavior can be dangerous, but that can be worked around, and otherwise it's super convenient. Going ahead and closing this issue.
