### ISSUE TITLE
Join doesn't work correctly under Windows

### ISSUE THREAD

**Issue by Cthutu** [casey/just#1167]
When using join under Windows, it can produce a path string like "foo\bar".  But if the generated path is used in a variable, when utilising that variable, the back slashes are interpreted as escape characters.  So, for example, this does not behave correctly.

```
my_prog := join("foo","bar")

run:
    {{my_prog}}
```

The string generated in the run section will be "foobar" and not "foo\bar" as expected.

I think the escape characters should not be evaluated {{...}} but at the point of use of strings themselves.  Either that, or `join` should produce "foo\\bar", on Windows.

NOTE: this was run from Git Bash on Windows.  The workaround is to add `set windows-powershell` at the top.

**Comment by casey** [comment]
Thank you for opening this issue!

This is definitely a problem, although it's caused by a bunch of things working as intended:

- On Windows, `join` uses `\` to join path components
- On Windows, `sh` is the default shell
- `sh` treats `\` as an escape sequence

I'm not sure what the best way to fix this is. I've been considering adding a `/` operator for joining path components, so this:

```
join("foo","bar")
```

Could be written as this:

```
"foo" / "bar"
```

The `/` operator could always use `/` to join path components. It would be unfortunate that it doesn't work the same as `join`, but if using `/` always works, then it would be a backwards-compatible way of fixing this issue. `join` could be deprecated, and the documentation could guide people towards using `/`.

Additionally, even if you're on windows using `\` separated paths, you might want to use `/` anyways to join things like URL paths.

An annoying wrinkle is that although `/` is supported on Windows, it doesn't work for all paths, namely paths that use the extended length path syntax.

**Comment by runeimp** [comment]
Hey @casey what? I've never seen `/` not work on Windows. Do you have an example? Or a link to a discussion on this? Windows, always _soooo_ much fun.

**Comment by casey** [comment]
I haven't run into this problem myself, but it's documented [here](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd):

> The "\\?\" prefix can also be used with paths constructed according to the universal naming convention (UNC). To specify such a path using UNC, use the "\\?\UNC\" prefix. For example, "\\?\UNC\server\share", where "server" is the name of the computer and "share" is the name of the shared folder. These prefixes are not used as part of the path itself. They indicate that the path should be passed to the system with minimal modification, which means that you cannot use forward slashes to represent path separators, or a period to represent the current directory, or double dots to represent the parent directory. Because you cannot use the "\\?\" prefix with a relative path, relative paths are always limited to a total of MAX_PATH characters.

**Comment by casey** [comment]
It's only an issue with paths that start with `\?`, and I'm not sure how common they are. I do know that Rust's canonicalize function returns a `\?` path.

**Comment by runeimp** [comment]
I've never in my life, and I started with DOS 3.0 almost 40 years ago, and often work with Windows 10 systems at work and for gaming at home, have I ever used `\?` to prefix a path or even seen it used in anything or mentioned in a tech document. This is the very first time I've heard of it. Now I could be wrong. But I think it's safe to ignore that potential issue. Anyone else have different experience?

**Comment by Cthutu** [comment]
`\?` are not common but they do exist and are legitimate.  Usually filenames are restricted to 260 characters (as defined by MAX_PATH macro), but this prefix bypasses that restriction.  This horrible hack is to stop buffer overflows on old software that only catered for 260 characters.  Old software just doesn't handle it.

I've personally had to use it for situations with large deep folder hierarchies.

**Comment by runeimp** [comment]
Check for `\?` in the first argument and if it doesn't exist use `/` on Windows in stead of `\`? Not 100% bullet proof, but once again, how often will it matter? Also note that this is currently broken as-is. I could be wrong but I believe changing the behavior now as suggested is unlikely to break it more and will likely fix the situation 99.999% of the time.

**Comment by casey** [comment]
I'm hesitant to change the existing behavior, even though it's undesirable, since it could break someone who's using PowerShell on Windows, with some application that doesn't expect back slashes.

What do you think about #1237, which I just opened? It adds a `/` operator, which joins strings using a `/` character on every platform. This is easier to type and looks better than `join(a, b)`. Additionally, if users want `join` to use back slashes on windows, this would give them a way to do things like join a path to a URL.

**Comment by rocket-matt** [comment]
I've just started using Just again and the problem still persists on Windows in other areas.  Using `{{justfile_directory()}}` produces a path with the slashes omitted.  For example, if your current directory is `C:\Foo\Bar`, `{{justfile_directory()}}` returns `C:FooBar`.

**Comment by casey** [comment]
@rocket-matt That's quite annoying! We can't change the default behavior, but we could introduce a setting that used forward slashes instead of backslashes for just functions.

**Comment by casey** [comment]
This is mostly fixed, although I'm going to open an issue to explore the idea of using `/` paths everywhere, likely with a setting.

**Comment by W1M0R** [comment]
This is somewhat related:

1. https://github.com/watchexec/watchexec/issues/830

I'm using watchexec in a just recipe:

```justfile

src_dir := clean(absolute_path("src"))

run-dev:
  echo "src_dir: {{src_dir}}"
  echo "$(pwd)"
  pwd
  cd src

dev-go:
  watchexec \
    --shell=none \
    --restart \
    --notify \
    --no-meta \
    --ignore "*node_modules*" \
    --ignore "*_templ.go*" \
    --ignore "*-lock.json*" \
    --ignore "*xui/messages/*" \
    --ignore "*project.inlang*" \
    --ignore "*dist*" \
    --ignore "*public*" \
    --ignore "*pb_data*" \
    --exts go,tpl,tmpl,html,js,json,css,html,toml \
    -vv \
    -- \
    just run-dev
```

The output of `just dev-go` is:

```pwsh
[Running: just run-dev]
src_dir: \\?\C:\Users\user2\sdl\labs\sdl-web\sdl-web-demo-7\src
echo "$(pwd)"
Microsoft.PowerShell.Core\FileSystem::\\?\C:\Users\user2\sdl\labs\sdl-web\sdl-web-demo-7
pwd

Path
----
Microsoft.PowerShell.Core\FileSystem::\\?\C:\Users\user2\sdl\labs\sdl-web\sdl-web-demo-7

cd src
Set-Location: Cannot process argument because the value of argument "path" is not valid. Change the value of the "path" argument and run the operation again.
```

I'm not sure whether `just` should handle UNC paths, or just leave them as is. In my mind, this is a regression in `watchexec`, and it should not be using UNC paths to begin with (or at least, allow people to opt out). I was hoping the just `clean` function would just normalize the path and remove its UNC qualities, but this was a long shot.

Just leaving this message here in case someone else is trying to figure out whether `just` needs better UNC support or not.
