### ISSUE TITLE
About zh-CN translation

### ISSUE THREAD

**Issue by hustcer** [casey/just#1200]
Just is one of my daily used tools, so I'm interested in updating the outdated [zh-CN](https://github.com/chinanf-boy/just-zh) translations (I have translated the nushell book to zh-CN [here](https://www.nushell.sh/zh-CN/book/)). Will you accept a PR like `README.zh-CN.md`?  And I will update it from time to time, maybe monthly.
Or I can create a translation repo myself, which one do you prefer?

BTW: 
The [book](https://just.systems/man/) seems to be generated from `README.md`?

**Comment by casey** [comment]
That would be awesome. I don't think thattranslation has been updated since it was written.

Should we use the shorter 2-letter language code? I.e. `README.zh.md`, or maybe `README.chinese.md` or `README.中文.md`? I think we should use whatever is most likely to be recognizable to chinese readers, even if it's not an official ISO language code.

> And I will update it from time to time, maybe monthly. Or I can create a translation repo myself, which one do you prefer?

If it's convenient for you, let's put it here, alongside the existing `README.md`. I think people are more likely to see it that way. Whenever you open a PR I'll just smash the merge button since I don't read any Chinese 😅

That's right, the book is generated from README.md using [this rust binary](https://github.com/casey/just/blob/master/bin/generate-book/src/main.rs). If we have a Chinese `README.md`, I can use the same tool to generate the book and publish it to `https://just.systems/man/zh/` or `https://just.systems/man/中文/`.

**Comment by hustcer** [comment]
Great, then let's use `README.中文.md`, I like this name. I will translate it in the following week

**Comment by casey** [comment]
Awesome! Want to just translate the first section, or some smaller part, and open a PR with just that? I find that it's easy to break up things into smaller pieces, both when coding and when writing, and doing it all at once might be a big undertaking.

**Comment by hustcer** [comment]
Agreed, I will break it into smaller pieces

**Comment by hustcer** [comment]
Available here: https://just.systems/man/zh/
