### ISSUE TITLE
Allow quotes in arguments to be preserved

### ISSUE THREAD

**Issue by schicks** [casey/just#1214]
I have a just command that looks like this;
```
test *ARGS:
  python -m pytest --ff -x {{ARGS}}
```
I want to use it like this;
```just test -m "not slow"```
However, when I do that the command is expanded to this;
```python -m pytest --ff -x -m not slow```
I need some way to preserve the quotes that I passed as an argument. I can't figure out how to do this from the README, though I would totally believe that I am missing something that already exists.

**Comment by casey** [comment]
Hi @schicks, the best way to do this is to pass the arguments as positional arguments, and then consume them using `"$@"`:

```
set positional-arguments

test *ARGS:
 python -m pytest --ff -x "$@"
```

I think that passing arguments with spaces/whitespace splitting/quoting/etc deserves its own section in the readme, since it's a common source of confusion/questions. I'm on a trip, but when I get back I'll write it.
