### ISSUE TITLE
'/' operator not in current release (1.2.0)

### ISSUE THREAD

**Issue by dt665m** [casey/just#1281]
@casey just getting started here (heh).  As of 1.2.0 (current release as of this writing), this operator doesn't exist but the docs/book/readme describes things as if it does.  I know there is a lot to synchronize and it'll be a non-issue soon.   For those that are running into this currently, I'm installing from master using ```cargo install --git https://github.com/casey/just just```.

Thanks for the amazing work!

**Comment by casey** [comment]
Thanks for the note! This is unfortunately a recurring problem, I'll add a feature and add it to the readme, but then it might take a some time to make it into a release, and then there's confusion.

Some things that might help:

- Release more frequently, potentially after every new feature. I kind of don't want to do this, because I like to have a little time for a feature to be in master, and potentially get a few users who might discover problems with it, before it makes it into a release.
- Avoid building https://just.systems/man/en/ from master, and instead only update it on new releases. The readme would still be out of date, but we could add a note. One downside of this is that improvements to the readme would need to wait for a release to be published, even if they weren't related to a new feature.

**Comment by casey** [comment]
I just released [1.3.0](https://github.com/casey/just/releases/tag/1.3.0), so path operator away! In the future, I think I'll try to set a calendar reminder of like a week or so after I add a new feature to cut a release, to minimize the time that a new feature is documented in the readme but unavailable in a release.

**Comment by casey** [comment]
> Thanks for the amazing work!

And thank you for the kind words!

**Comment by runeimp** [comment]
To help alleviate the problem maybe you could add the update to the README with a consistent suffix like `(not yet released)` that you can search for and update by either deleting the suffix or by replacing with a new one like `(available in version 1.3.0+)` or some such. I always appreciate little notes that let you know when a features was added to the language. Though Just is not a full blown programming language I think its API could be tracked with the same mindset. Also I believe those notes can still be quite valuable for CI/CD integrators, etc.

**Comment by casey** [comment]
That's a good idea, I'll try to add notes like that going forward. I can also add something to the release script that panics if it sees `(unreleased)` or `(master branch)`.

**Comment by casey** [comment]
> Though Just is not a full blown programming language…

Someone needs to implement #792 so I can defend `just` against such unfair slander 😁
