### ISSUE TITLE
Show a message if a newer version is available

### ISSUE THREAD

**Issue by beardgans** [casey/just#1287]
Hi everyone!
And thank you for this awesome project!

I found this feature very useful in the [GitHub CLI application](https://github.com/cli/cli/blob/trunk/internal/update/update.go) and [npm](https://github.com/npm/cli/blob/latest/lib/utils/update-notifier.js).

I think it'll be useful for users who install `just` using the installation script or `cargo`.
And this will let them know that a new version is available and it's time to update.

Ready-made crates to do that:
* https://github.com/mgrachev/update-informer
* https://github.com/tarikeshaq/update-notifier

**Comment by runeimp** [comment]
I like that idea but I think there is a barrier to outputting anything other than what is expect even on `stderr` because of Just's usage in CI/CD systems. Though I could be wrong. Maybe this could be a flag or settings feature. Maybe it could be something Just does when `--list` is called and thus not be a barrier to CI/CD systems? Or is it possible that some CI/CD systems do use `--list`?

**Comment by casey** [comment]
I like this idea, but think it would often be annoying. Users often use `just` via a package manager, and thus sometimes can't install the latest version, since it hasn't made it into the repository they're installing from.

Also, `just` has very few bugs (fingers crossed this continues!), so there isn't usually a pressing need to upgrade.

**Comment by dbready** [comment]
I do not like my development tools making unexpected network calls. Especially if a naive implementation causes this to block what should otherwise be fast local operations.

**Comment by casey** [comment]
I think I'm going to close this. It would be annoying on CI, or in other places where the new version can't be installed. Also, I agree with @dbready that random outgoing network calls are distressing.
