### ISSUE TITLE
Table of Contents in Readme?

### ISSUE THREAD

**Issue by riotrah** [casey/just#1318]
Hi!

Love just, thanks for the incredible work, @casey et al.

Wondering if the book generation would preclude adding a TOC to the readme.

Maybe there's a way to only have one render on GH or something. I recall a variant of MD once, perhaps from a library or some other case, that would let you use a `[toc]` block or something and auto generate one from the header lines. 

Maybe it might be a good first issue if you thought it would add value (it certainly would for me) without adding overhead.

**Comment by casey** [comment]
Thank you for the kind words!

There is actually a TOC in the readme, but it's super easy to miss. I even made a little arrow and people still miss it:

<img width="925" alt="Screen Shot 2022-08-28 at 10 27 16 PM" src="https://user-images.githubusercontent.com/1945/187129125-0187f5d0-73bf-40b1-a6b9-2e4041677920.png">

They really need to make it possible to stick it into the readme.

I'd consider auto-generating one and sticking it into the readme, but I've found that having to keep that kind of thing in sync, or having CI fail on contributions because you didn't run a script is really annoying. Definitely complain to GitHub though for their terrible UX on this one!
