### ISSUE TITLE
Unordered named recipe argument flags

### ISSUE THREAD

**Issue by Jarthianur** [casey/just#1404]
Hi folks,
I couldn't find any open issue on this thingy, hence I'm creating this one now.
So far *just* seems to support only positional arguments to recipes from a callers perspective (! not the "positional arguments" feature). Meaning that the order of args passed to a recipe matters and there are no named flags designating the parameter to which an arg will be bound to. It's actually the most natural thing to pass args to a cli-tool via flags (e.g. `tool --param arg`) without caring about the order.

It would be extremely helpful, if *just* would support a feature like that. Why?
Well two things come into my mind at this point. First, for readability reasons. It happens sometimes, that a recipe has quite a few args and passing them in correct order without designating what which arg actually is might cause confusion and errors. Imagine some maintainer changes the order of args in a recipe for whatever reason. This would break a lot. The second reason is mainly about default values for args. A recipe may have a dozen args and all of them have default values, but you want to set the last one only. In this case one has to pass them all, just to make the change to the last one unambiguous.

**How would a possible solution look like?**
*just* should accept args passed to a recipe in a typical CLI manner using flags as designators, where the order of passed flags does not matter to the recipe, while still supporting the old positional behavior where no flag is given. Example:
```
# justfile
do-magic arg1="dust" arg2="dust.txt":
    echo {{ arg1 }} > {{ arg2 }}

# shell
just do-magic --arg1 "hello world" --arg2 test.txt
# or equivalently
just do-magic --arg2 test.txt --arg1 "hello world"
# or even
just do-magic --arg2 ash.txt
# or on steroids
just do-magic --arg2 out.txt "content"
```

In an more advanced implementation (future music), *just* could support short-hand flags to each arg. Example:
```
# justfile
recipe long_param(l):
    echo {{ long_param }}

# shell
just recipe --long_param hello
just recipe -l world
```

AFAICT, this feature would neither break compatibility to current syntax, nor change the behavior of current justfiles/scripts (well maybe autocompletion needs to be adjusted). I sadly do not have the time, or required rust-skills to take on work on this myself, but are definitely willing to support where I can.

**Comment by runeimp** [comment]
It's hard to understand what you are trying to solve exactly. There is nothing stopping you from passing options that get used by the internal recipe code. But recipes are not automatically functions or scripts. Just is a task runner intended to replace `make` in situations where it is used as a task runner instead of a code builder. So any input for a recipe is expected to be handled by the tasks, code, etc. within the recipe itself.

If you code a recipe as a shebang script, _your script_ should handle the recipe input as needed, or the various tasks should be passed whatever input is appropriate based on how you designed the signature of the recipe. I believe there are some tools out there that may do what you're expecting as a specific feature of the tool. But `just` is not one of them. And I believe this was discussed much earlier in the projects life cycle. It is also used _a lot_ on many projects, often by automated systems as well. The changes you're asking for would likely break a large portion of them out-of-the-gate if implemented.

@casey do you have any thoughts? I have a feeling I'm overlooking something regarding all of this.

@Jarthianur I have a feeling I'm being harsh in my response. If that is the case please forgive me. I'm not feeling quite right today but wanted to give you some feedback on your request.

**Comment by casey** [comment]
I don't think this is a terrible idea, but there's actually an issue open for this, #476, so closing as a duplicate. Check out #476.

This would be a backwards incompatible change, since it's possible to pass flags as a recipe argument:

```
foo arg:
  echo {{arg}}
```

```
$ just foo --bar
echo --bar
--bar
```

The version proposed in #476 requires declaring that arguments will be accepted as a flag, so as to be backwards compatible:

```
foo --arg:
```
