### ISSUE TITLE
default opt out of janus / improve docs

### ISSUE THREAD

**Issue by satirical-eraser** [casey/just#1431]
https://github.com/casey/just#janus seems auto. can be opt out by default OR clarify what dev will do when this get run on a project? repos are public yeah but user may not appreciate scrapping their data or want unwarrant/expected issues/pr for justfile in their project

**Comment by casey** [comment]
Usually when I run janus, I'm trying to figure out if change to just breaks existing justfiles. These days, this would only happen if it were due to a bug fix, since just has reached 1.0 and has strong backwards compatibility guarantees.

The workflow is something like:

- Download justfiles from public GitHub repositories
- Check justfiles against new version of just to see if the never version of just breaks them
- If there are enough justfiles that break, I'll probably decide against making the change
- If there are few justfiles that break, I'll open issues on the repos that contained the justfiles, or even a PR with a fix, if the fix is easy

Downloaded justfiles are already public, and issues warning developers about potential future breakages seem unproblematic.

**Comment by casey** [comment]
I'm open to how this could be improved, but I think the current behavior is fine.
