### ISSUE TITLE
Snap store version is old

### ISSUE THREAD

**Issue by akshaybabloo** [casey/just#1432]
The Snap store version on Ubuntu is on 1.2.0. Are you able to update it please?

**Comment by casey** [comment]
I originally created the snap store version, but since then I stopped using Ubuntu, so I think it's impractical for me to continue maintaining the snap store version. (I had a server that was running Ubuntu, which I used to package it, but I've since switched it over to Debian.)

I can't maintain packages for OSes that I don't use, it's just way to time consuming in addition to maintenance, so the best way forward here is probably to set up something that publishes the latest version on CI automatically: #1249

I'm going to close in favor of that issue, to focus attention there.
