### ISSUE TITLE
Consume/run/list makefile commands

### ISSUE THREAD

**Issue by stephen-digicert** [casey/just#1490]
Hear me out, I know this is a nitpick.

How feasible is it for Just to have an option to read and run makefile commands if a makefile is present?

Use case: Just is used as the daily driver and have my own local justfile, but the rest of the org and teams use makefiles. Convincing them to switch over to Just hasn't made any headway. One reason is that make is often installed by default on new systems, making it very portable.

Just being able to list make commands and run them would by highly valuable in this use case, as the user could use their local justfile while also being able to call `just build-dev` and take advantage of the existing makefile and any variables existing in that file.

Again, nitpick, curious about your thoughts

**Comment by casey** [comment]
I definitely see the use-case here. In addition to being less-widely available, Just doesn't replace Make as a build system, so even a project that adopts Just as much as possible, may still have a makefile, or may be using some other build system.

A easy and general way to support this use-case would be to have a "fallback command" setting. If the user ran a just invocation with unrecognized recipes, those unrecognized recipes could be passed to the fallback command. Something like this:

```just
set fallback-command := "make"
```

However, this would have undesirable consequences. For example, if you misspelled a recipe, Just would pass it to make, and you would get an error from make, instead of the just error.

Have you considered using forwarding recipes in your justfile? For example:

```just
build:
  make build
```

This would have the disadvantage that you would have to add a Just recipe for every Make recipe you wanted to be able to run from Just, but the error messages would be better..

**Comment by stephen-digicert** [comment]
I like the forwarding idea. That should be easy to auto-generate (with a Just command)

Thanks!
