### ISSUE TITLE
Alias commands do not work as expected

### ISSUE THREAD

**Issue by bdparrish** [casey/just#1491]
in my `.zshrc` I have aliased python to be...

```bash
which python
python: aliased to /opt/homebrew/bin/python3
```

and here is my python3

```bash
which python3
/opt/homebrew/bin/python3
```

However, this fails but if i replace `python` with `python3` then it succeeds. Is there a weird quirk to be aware of here?

```justfile
current-app-version := `python ./app/_version.py`
```

**Comment by casey** [comment]
`just` uses `sh` by default, so it won't run any zsh-specific configuration. And `just` doesn't start an interactive `sh`, so I'm not sure which init scripts it will run if any. You could consider using `python3` in your justfiles, so that they're self-contained and explicit, and don't depend on external configuration to work.
