### ISSUE TITLE
Make a video

### ISSUE THREAD

**Issue by casey** [casey/just#152]
I think a quick terminalcast is probably the best way to convey what just does.

- make a new folder
- cd into that folder
- start a new project
- initialize a rust project
- demonstrate every feature
- show error messages

**Comment by casey** [comment]
Should also show off error messages, since this is a nice feature of just

**Comment by dewan-ahmed** [comment]
Hi @casey are you thinking of something like asciinema or an actual screen-recording with voiceover? 

Do you really want [every feature](https://just.systems/man/en/chapter_20.html) to be shown in this video? Is the goal to get a user *get started* with just? Would showing 3/4 major features suffice? If yes, please suggest which features you'd like to be included in the video.

**Comment by casey** [comment]
Hi @dewan-ahmed! Every feature is probably overkill, since there are more than a few at this point. I think the goal should be to get started with just, and highlight some features that are likely to be helpful. I don't have strong opinions about which features are best, but at least recipes, dependencies, the default recipe, passing arguments, and setting variables. I would like an asciinema recording for the readme, but a screen-recording with voiceover would be cool too.

**Comment by dewan-ahmed** [comment]
@casey makes sense. Feel free to assign this to me and I'll be uploading the first draft of the asciinema by next Monday.

**Comment by casey** [comment]
@dewan-ahmed Dope!

**Comment by dewan-ahmed** [comment]
hi @casey 

here's the asciinema recording: https://asciinema.org/a/g82M0Xk2TN00chtDhjbdotYcr

but this shows the actual echo and sleep commands before the command output

so attaching a quicktime recording as well


https://user-images.githubusercontent.com/30604461/197462966-07e103b9-b80f-42d5-8d86-ea58a6d1f36d.mp4

I had to compress the video (GitHub file size limitation) using an online tool and that's why there's a watermark of **clideo**

If you don't want the watermark, I can link a google-drive version of the uncompressed file.

**Comment by casey** [comment]
Nice, thank you! Can you link the uncompressed file?

**Comment by dewan-ahmed** [comment]
[uncompressed video](https://drive.google.com/file/d/1hKhvAxWCnz6E9cEO9YIYpo4Xha7_23nA/view?usp=sharing)

**Comment by casey** [comment]
@dewan-ahmed Awesome, cheers!
