### ISSUE TITLE
Maintained vscode-just

### ISSUE THREAD

**Issue by Nugine** [casey/just#1576]
Sadly there are no active forks now.
<https://github.com/skellock/vscode-just/forks?include=active%2Carchived%2Cinactive%2Cnetwork&page=1&period=&sort_by=last_updated>

The most recent fork [sclu1034/vscode-just](https://github.com/sclu1034/vscode-just) has been archived by the owner on 2023-01-02.

**Comment by runeimp** [comment]
I don't use VS Code so I don't use that extension in it, but, does it need activity? After a point lots of these types of extensions don't need much if any activity to remain viable. Looks like the current issues in the @skellock version are not necessarily deal breakers (I just glanced so could be completely wrong) and I'm guessing the other forks maybe cover at least one of those issues. Is it fundamentally broken or just not active and you need something changed about it?

**Comment by Nugine** [comment]
[sclu1034/vscode-just](https://github.com/sclu1034/vscode-just) only works as a syntax highlighter for now.

It pops `Parsing error reading justfile.` when I try to run the command `Just: Run Recipe`. While I can run recipes via cli, I still hope that the extension can be fixed.

**Comment by runeimp** [comment]
Yep, sounds pretty broke. I personally would just use the command line in VS Code's Terminal but that is me.

Unfortunately, I don't believe there is any official maintenance for 3rd party tools to be found here. They are all, to my knowledge, strictly available due to the generous nature of their individual developers. VS Code and Just are both pretty popular so it is a bit surprising that support is falling by the wayside though.

Does anyone (@casey) know of any VS Code extensions that have better support lately?

**Comment by skellock** [comment]
Hey... ya, sorry about my `vscode-just` library. I wasn't able to keep up.

More than happy to hand it off if someone!

**Comment by Nugine** [comment]
> Hey... ya, sorry about my `vscode-just` library. I wasn't able to keep up.
> 
> More than happy to hand it off if someone!

Thanks for your work! This issue is to make users aware of the chance.

**Comment by muuvmuuv** [comment]
There is a fork which has a few updates: https://gitlab.kokakiwi.net/contrib/vscode/vscode-just

Things that would be neat:
- Formatting (remove empty multilines, indention alignment)
- Inline "Run task"
- Separate color for `@` starting lines to quickly identify muted output
- Maybe via language server highlighting for shell tasks
- Better highlighting for env var `{{just_executable()}}`

**Comment by nefrob** [comment]
@muuvmuuv I'm slowing working on building out an extension here: https://github.com/nefrob/vscode-just. Once the highlighting of escaped blocks (i.e. `{{...}}` as mentioned above) is solid I can pivot to other VSCode integrations like formatting. Feel free to raise an issue or PR for any desired features in the meantime.

If we want full LSP support it would probably be best to see that provided by `just` directly so it can be used by extensions for multiple editors.

Update 5/14/2024: noticed vscode has an open issue on tree-sitter grammar support (https://github.com/microsoft/vscode/issues/50140). Once tree-sitter is supported it will likely be the preferred extension method since textmate grammars (what the extension listed here uses) can't parse escaped blocks including strings like `'{{ 'inner string' }}'` effectively.

**Comment by casey** [comment]
I opened #2034 to update the readme to point to `nefrob/vscode-just`, since that seems to be the most actively maintained.

**Comment by skellock** [comment]
Thank you!

In `just` we `trust`!

**Comment by mkhl** [comment]
fwiw i just published https://marketplace.visualstudio.com/items?itemName=mkhl.mkhl-just which doesn't do syntax highlighting but helps with formatting justfiles and running recipes
