### ISSUE TITLE
just <folder> doesn't run default in `Justfile`

### ISSUE THREAD

**Issue by rocket-matt** [casey/just#1581]
# Bug

Given a just file found at `foo/Justfile` containing:

```
default:
    just --list
```

and after running `just foo`, it complains it can't find `justfile` (notice lower-case `j`).

# Expected

It was expected to see the list of recipes in `foo/Justfile`.  Notice, running `just foo/my-recipe` works fine.

# OS

Pop_OS! Linux based on Ubuntu 22.04.

**Comment by runeimp** [comment]
Casing doesn't matter to Just. You can also have `some_file-name.just`.

When you execute Just it searched the current directory and those going towards the root directory looking for a Justfile of some sort. It does not check subdirectories to the current directory unless specifically told to do so. Like how you mentioned with `foo/my-recipe`. It worked there because you specified the directory as part of the 1st argument so Just checked if that directory existed then checked that directory for a Justfile to see if there was a `my-recipe` recipe to call.

**Comment by rocket-matt** [comment]
I have discovered it works if you use `just foo/` (note the slash).

So, if this is intended functionality (I can see why it might be because there might be a recipe called foo), then disregard this issue.

However, perhaps the functionality of looking for `foo/justfile` when typing `just foo` if and only if there isn't a `foo` recipe in the root would be useful?

**Comment by runeimp** [comment]
Yes that is intended functionality.

I'm pretty sure this was brought up early in Just's development and was decided against. I like that sort of functionality myself, but it does lead to potential ambiguity and this tool is now used in lots (several thousand ?) of CI/CD setups so even more likely not to change at this point.
