### ISSUE TITLE
mvn: command not found in justfile

### ISSUE THREAD

**Issue by fmarchioni** [casey/just#1677]
I am unable to execute the mvn command from within a just task.
The mvn command is available in my OS PATH:
```
mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /home/francesco/apache/apache-maven-3.8.4
Java version: 17.0.2, vendor: Oracle Corporation, runtime: /home/francesco/java/jdk-17.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.0.12-100.fc35.x86_64", arch: "amd64", family: "unix"
```
And my 'which mvn':
```
which mvn
~/apache/apache-maven-3.8.4/bin/mvn
```

I have used the following justfile:
```
# Justfile

# Build the project
build:
    mvn clean install

# Run tests
test:
    mvn test

```
By executing the just build results in the following error:
```
just build
mvn clean install
sh: line 1: mvn: command not found
```
To get it working, I have to include the full path to the mvn binary
```
build:
    ~/apache/apache-maven-3.8.4/bin/mvn clean install
```

**Comment by laniakea64** [comment]
> The mvn command is available in my OS PATH:

How are you adding it to your OS PATH?

**Comment by fmarchioni** [comment]
Hi, I'm defining my PATH in ~/.bashrc 

```
PATH="~/apache/apache-maven-3.8.4/bin:$PATH"
# other PATH. . . .
export PATH
```

**Comment by laniakea64** [comment]
One option would be to tell `just` to use `bash` as shell instead of `sh` for this justfile - https://just.systems/man/en/chapter_25.html#bash

Another possibility might be to define your PATH in `~/.profile` instead of `~/.bashrc`, then log out & back in for it to take effect.  Not sure this works in all graphical desktop environments though.

Edit: It's also possible to explicitly define this part of the path in the justfile -
```
export PATH := env_var('HOME') / "apache/apache-maven-3.8.4/bin:" + env_var('PATH')
```

**Comment by fmarchioni** [comment]
Thanks @laniakea64 ,
`set shell := ["bash", "-uc"]`
works perfectly. I'll close this issue. 
Thanks for your help
