### ISSUE TITLE
How to activate a shell using just?

### ISSUE THREAD

**Issue by ylhan** [casey/just#1683]
I want to wrap the creation and activation of a python shell in a just command. The problem is that the activation doesn't propagate up to my current shell.
```just
setup:
    pyenv exec python -m venv .venv
    source .venv/bin/activate
```

Calling `just setup` is fine but `which python` suggests that the venv was not activated. I believe this is possible in a [Makefile](https://stackoverflow.com/questions/33839018/activate-virtualenv-in-makefile)

```bash
$ which python
/Users/allenhan/.pyenv/shims/python
$ just setup
pyenv exec python -m venv .venv
source .venv/bin/activate
$ which python
/Users/allenhan/.pyenv/shims/python
```

I want:
```bash
$ which python
~/.../.venv/bin/python
```

**Comment by benjamineskola** [comment]
I believe you can only ever activate it for the same process or for subprocesses. You can't modify the environment of the parent process. This is true of makefiles as well. The link you give for makefiles contains only answers for modifying the make environment, not propagating up to the parent shell.

(_Within_ just you might need to use a `#!/bin/sh` line in your recipe, otherwise the activate will only take effect for a single line.)

**Comment by runeimp** [comment]
Try something like...

```sh
setup:
	#!/bin/sh
	pyenv exec python -m venv .venv
	source .venv/bin/activate
```

or

```sh
setup:
	#!/usr/bin/env bash
	pyenv exec python -m venv .venv
	source .venv/bin/activate
```

Using a shebang to start a recipe is essentially the same as running a script. Otherwise the execution is line by line and environment changes don't carry over from line to line unless your using a shebang.
