### ISSUE TITLE
Can just be compiled to WebAssembly?

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [casey/just#1747]
I want to run `just` without installing anything. I thought wasm may be a good tool for that.

**Comment by casey** [comment]
I don't know, since I don't think anyone's tried. I would try [wasmtime](https://wasmtime.dev/) or [wasmer](https://wasmer.io/).

**Comment by casey** [comment]
When you say you don't want to install anything, what do you mean?

**Comment by przemyslawjanpietrzak** [comment]
>  When you say you don't want to install anything, what do you mean?

Without any e.g. `brew install just`. Just download `just.wasm` file and run it via wamstime/wasmer

**Comment by casey** [comment]
Can you download a release binary? That would let you avoid installing `brew`.

The latest releases are [here](https://github.com/casey/just/releases), which includes binaries for various platforms. 

You can also use the install script, like so, which will download the latest release:

```
curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to DEST
```

**Comment by mofosyne** [comment]
As a possible alternative, looks like someone figured how to compile JustFiles into portable shell scripts. This does mean that if you change the justfile, you need to run the recompiler again however.

https://github.com/jstrieb/just.sh

It's in python rather than rust unfortunately, so would need to be ported if you want to bake it into just.
