### ISSUE TITLE
Unexpected behaviour when using curly braces in arguments

### ISSUE THREAD

**Issue by AlessandroZanatta** [casey/just#1753]
# Description
I am using just to wrap calls to a kubernetes cluster using `kubectl` commands. When trying to patch a resource using JSON I have encountered some surprising behaviour related to curly braces.

Here's a little PoC with some examples.

Is this intended behaviour? I could not find documentation for this. Moreover, a quick glance at the code did not reveal the source of the issue. Please, let me know if I am `just` doing something wrong.

## Example `justfile`

```
echo ARGS:
  echo {{ARGS}}
```

### Working as expected
```
$ just echo test
echo test
test
```

```
$ just echo {test}
echo {test}
{test}
```

### Unexpected behaviour
```
$ just echo '{test,echo,foo}'
echo {test,echo,foo}
test echo foo
```
Expected:
```
echo {test,echo,foo}
{test,echo,foo}
```

Here just seems to "lose" a pair of quotes:
```
$ echo '{test,echo,foo}'
{test,echo,foo}
$ just echo '{test,echo,foo}'
echo {test,echo,foo}
test echo foo
```
```
$ echo "'{test,echo,foo}'"
'{test,echo,foo}'
$ just echo "'{test,echo,foo}'"
echo '{test,echo,foo}'
{test,echo,foo}
```

# Version and shell info
Justfile version: 1.16.0
Shell: GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
OS: Arch Linux (btw)

**Comment by casey** [comment]
I think this is actually just normal shell behavior. `{…}` is handled specially by the shell. It expands to the prefix and suffix around `{…}`, with the `{…}` replaced by each comma-separated value inside.

Soo `{foo,bar,baz}` expands to `foo bar baz`, and `hi{a,b,c}foo` expands to `hiafoo hibfoo hicfoo`.

It's useful when renaming files, since you can do `mv foo.{txt,bin}`.

> OS: Arch Linux (btw)

😂
