### ISSUE TITLE
"::" module path separator complicates completion in Bash

### ISSUE THREAD

**Issue by crdx** [casey/just#1857]
I've been test-driving modules recently, and the `::` module separator is causing me some issues with shell completion in Bash.

The `COMP_WORDBREAKS` variable controls which characters are considered word breaks. The default is `"'><=;|&(:`, which contains a `:`. This prevents module recipes, which are in the format `mod::recipe`, from completing.

So I put

```bash
export COMP_WORDBREAKS="${COMP_WORDBREAKS/:/}"
```

in my bashrc, and this seemed to fix it.

However, _sometimes_ (and I can't replicate the trigger) when I complete a submodule name it completes as `mod\:\:` and then stops any further completing.

Not sure what the best way forward is, but I don't like having to modify `COMP_WORDBREAKS` because it's a global change and might have other unintended side-effects.

In fact, if the Bash default is incompatible with `:` then it might be a bad idea to use it, as it will leave many people confused. Defaults are king.

My initial thought as to an alternative would be `.` because it's conceptually similar, isn't present in the default `COMP_WORDBREAKS`, and isn't currently valid in recipe names.

**Comment by casey** [comment]
Damn, that is so annoying. I definitely want to use the `::` syntax inside of justfiles for module names, but I agree that if bash chokes on `::`, it would probably be better to use that for the output of `--summary`.

**Comment by crdx** [comment]
When you say "if bash chokes on `.`" I assume you mean `::`?

It is damn annoying as I like `::` more too.

**Comment by casey** [comment]
Whoops, yeah, that's what I meant.

Yeah, also, as a general strategy for just, I like to make the space of invalid inputs as large as possible, and the space of valid inputs as small as possible, for future backwards compatible upgrades. In this specific case, `foo.bar` is an invalid command-line option, so, in the future, I could add a feature which used the syntax `foo.bar`, and it would be backwards compatible, because previously it would be an error. However, if I allow `foo.bar` on the command-line, that syntactic space is then no longer available for future upgrades. This general strategy applies to command line options, recipe syntax, etc.

But in this case it's probably not too bad, since it's only for the command-line, and I can't imagine what I would use `foo.bar` for in the future.

**Comment by casey** [comment]
I think we can actually deal with this in our completion script: https://stackoverflow.com/questions/10528695/how-to-reset-comp-wordbreaks-without-affecting-other-completion-script

**Comment by crdx** [comment]
Good point. I did see that post but for some reason didn't pursue it. I've fixed it on #1863.

**Comment by casey** [comment]
Fixed in #1863.
