### ISSUE TITLE
Consistent current directory of an included justfile

### ISSUE THREAD

**Issue by nyurik** [casey/just#1884]
I think there is a significant problem with the justfiles.  Recipe authors always assume that a receipe runs with PWD set to the same dir as the justfile itself.  This assumption is broken when one file is included in another file.  Assuming these two files:

```
# justfile
include 'subdir/justfile'

a:
  echo "a = $PWD"
```

```
# subdir/justfile
b:
  echo "b = $PWD"
```

If a user runs `just a` or `just b` from the top dir, both targets print the same top dir path.  But if i run `just b` while inside the subdir, it will print a subdir path.

I think it would be more consistent if receipe always used the path of the **current** justfile as the context PWD?

**Comment by casey** [comment]
`imports` behave as if the recipes in the imported justfile were included in the justfile directly, so the current directory of the importing justfile is the working directory for those recipes. This is contrasted with modules, `mod foo "some/justfile"`, which are independent justfiles with their own working directory. There are situations where you can make the case for both kinds of behavior. You might import a justfile which provides utility recipes which should run in the importing crate, since where they're imported from isn't important. Or, you might import recipes which interact with files in the directory that they're imported from.

 What's your use-case? Can you use modules instead?

**Comment by nyurik** [comment]
@casey thanks, I was not aware of the `mod` feature!  My only concern is global vars and optimizing "subtasks":

The root justfile has global variables, e.g. DB connection string.  These variables are used in many recipes, and may have some default, but often get set by user with `just foo=bar reciepe` pattern.  Many just recipes call other recipes, and want to pass all those params - so often I have to deal with #1762 problems - construct the "invocation variable" `my_just` that concatenates (and escapes) needed params, so I use it with  `{{ my_just }} subreceipe` calls as needed.

The problem is that now I have far too many of these recipes and need to reduce the size of the root justfile. Since my project has sub-domain areas, I could use modules with `just foo=bar area command <params>` pattern.

I agree that includes may need a different pattern, e.g. a user could create a dedicated subdir for justfile includes, and just keep them all there.  As long as they are not named `justfile`, it should be fairly consistent.  Actually naming sub-files `justfile` is what i think would break most things - because being in a subdir would cause subdir's justfile become the root, and change the PWD context

**Comment by nyurik** [comment]
P.S. unrelated - in the docs about the `mod` feature, I think this type of styling the minimal version may be easier to read (from [here](https://vega.github.io/vega/docs/transforms/#basic-transforms)):

![image](https://github.com/casey/just/assets/1641515/d7da0aa5-2200-4b2a-9884-70483f1b9686)

**Comment by casey** [comment]
Gotcha, good context to know! Okay, in that case I think this is okay, as long as using `mod` works. I think that kind of formatting for version requirements would be great, feel free to open a PR!
