### ISSUE TITLE
Interactive just examples

### ISSUE THREAD

**Issue by nalgeon** [casey/just#1893]
Hi Casey! Thank you for this awesome project!

Would you be interested in making the examples in the docs interactive for better understanding? Here is [what it could look like](https://codapi.org/try/just/).

If you're interested, I'll be happy to send you a PR.

**Comment by casey** [comment]
This is very cool! I think it should probably live outside the readme proper, since I want it to be possible to read the readme as just markdown, and transform it into a manpage, and other kinds of non-HTML formats. I think it might be nice to have a section of the readme which links to blog posts and other external docs, and a link to this could go there.

**Comment by nalgeon** [comment]
The [readme](https://raw.githubusercontent.com/casey/just/master/README.md) already has HTML in it :)

This is how it would look with interactive code examples:

````
Try running `just --version` to make sure that it's installed correctly:

```
just --version
```

<codapi-snippet sandbox="just" editor="basic">
</codapi-snippet>
````

So it's the same readme, but with an extra `codapi-snippet` tag for each code example. The tag is ignored when rendering on GitHub and can be skipped when transforming to other formats.

Creating a duplicate interactive readme outside of the `just` documentation website kind of defeats the purpose, since no one will read it. But it's up to you, of course.

**Comment by nalgeon** [comment]
Okay, no worries :) Let me know if you change your mind.
