### ISSUE TITLE
just should not require python for install

### ISSUE THREAD

**Issue by jeffrey-aguilera** [casey/just#1905]
And it certainly should not to try install something that does not exist:

==> Downloading https://ghcr.io/v2/homebrew/core/just/manifests/1.24.0
Warning: No available formula with the name "python" (dependency of just). Did you mean ipython, bpython, wxpython, pythran, jython, cython or ptpython?

(On github)

**Comment by casey** [comment]
`just` doesn't depend on python. The homebrew package isn't maintained by me, so I'm not sure what's going on there.

**Comment by runeimp** [comment]
Just for full disclosure...

1. There is a desire to have Python built-in to Just
2. If/When it happens it would note require Python as a dependency but would have Python "baked in"
3. There is no current timeline for making this happen

Everything I just said is true unless @casey disagrees with me because I'm sometimes a bit out of touch with the project but still use Just every day. 😇
