### ISSUE TITLE
Confusing error, expected function, but parameter of same name exists

### ISSUE THREAD

**Issue by Skgland** [casey/just#1959]
I would have expected the following to work

```
t A B="c": (q A ("e" + B) ("f" + B))

q R S T:
	echo {{R}} {{S}} {{T}}
```

```
$> just t "p"
error: Call to unknown function `A`
  ——▶ .justfile:21:15
   │
21 │ t A B="c": (q A ("e" + B) ("f" + B))
   │               ^
```

But it expects `A` to be a function instead of the Parameter.
Adding parenthesis around `A`, resolves the problem.

```
t A B="c": (q (A) ("e" + B) ("f" + B))

q R S T:
	echo {{R}} {{S}} {{T}}
```

```
$> just t "p"
p ec fc
```

I am probably missing something why the parenthesis are required, but anyway an improved error message in case a matching parameter exist might be warranted.

```
$> just --version
just 1.25.2
```

**Comment by casey** [comment]
Oof! Yeah that's a pretty unhelpful error message. It actually works without parentheses too:

```
t A B="c": (q A "e" + B "f" + B)

q R S T:
	echo {{R}} {{S}} {{T}}
```

Although it's pretty unreadable.

I can't think of a great way to produce a better error message. `X(…)` makes the parser think that the next item is a function call, which, combined with the fact that dependency arguments are space separated, makes this ambiguous. (This doesn't matter in a function call, i.e., `q(A, "e" + B, "f" + B)` because the commas prevent ambiguity.)
