### ISSUE TITLE
Special output format for commands

### ISSUE THREAD

**Issue by alinex** [casey/just#198]
It's great but I would like to better visually recognize which output lines are the called command and which are the command's output.

So I would like to prefix all command lines with `$ ` (dollar and space) and maybe format this lines in bold yellow in the console.

**Comment by casey** [comment]
Hi, Alexander! Thanks for the feedback!

I'm hesitant to prefix command lines with text, since it makes it harder to copy and paste them. Also, yellow is traditionally used to indicate warnings.

I actually recently added a`--highlight` flag, which prints commands in bold, which should render as brighter and/or bold on most terminals. Could you try the `--highlight` flag? I'm curious if you think it's visible enough. I would definitely consider making `--highlight` the default.

**Comment by casey** [comment]
I think that making `--highlight` the default behavior might be a good idea, and I'm interested in what other people think pro and con.

**Comment by casey** [comment]
I think `--highlight` is a good default, so I changed it in #512. I also added `--no-highlight`, so the old behavior can be recovered.
