### ISSUE TITLE
nix multi-line shebang is not handled by just

### ISSUE THREAD

**Issue by oux** [casey/just#2024]
Environment:
* nix 2.20.1 or later
* just 1.25.2

justfile:
```
hello:
  #!/usr/bin/env nix
  #! nix shell  nixpkgs#hello nixpkgs#cowsay --command bash
  hello | cowsay
```
Error:
![image](https://github.com/casey/just/assets/237991/a6d59947-9382-485b-a6f6-a642b708e59e)

Same shebang on a simple shell script file:
![image](https://github.com/casey/just/assets/237991/09b6f704-9a43-41db-acc5-8777937c472d)

Nix shebang documentation: 
   https://nixos.org/manual/nix/stable/command-ref/new-cli/nix.html#shebang-interpreter

**Comment by casey** [comment]
I think the reason this doesn't work is that when just extracts the body of a shebang recipe into a file to execute, `just` places the shabang line first, and then inserts blank lines before inserting the contents of the recipe, so that line numbers in error messages correspond to line numbers of the recipe.

So the way to fix this is to see if the next line is a shebang and put it at the top of the file.

So for example, this:

```just
hello:
  #!/usr/bin/env nix
  #! nix shell  nixpkgs#hello nixpkgs#cowsay --command bash
  hello | cowsay
```

Is currently translated to this:

```sh
#!/usr/bin/env nix

#! nix shell  nixpkgs#hello nixpkgs#cowsay --command bash
hello | cowsay
```

When it should be translated to this:

```sh
#!/usr/bin/env nix
#! nix shell  nixpkgs#hello nixpkgs#cowsay --command bash

hello | cowsay
```

**Comment by casey** [comment]
Fixed in #2276! All shebang lines are now kept together in the top of the resulting script.

**Comment by Enzime** [comment]
Tested this, #2276 fixes this for me 🎉

**Comment by casey** [comment]
Dope!
