### ISSUE TITLE
[question] How to blend shell functions within Just commands?

### ISSUE THREAD

**Issue by yurivict** [casey/just#2077]
My ~/.bashrc has:
```
dist() {bsub -I -app norm "$@"}
```

Is doesn't work in Just because this is sourced from ~/.bashrc

Is there a general way to use such shell functions in Just?

I also tried to set alias (alias dist := "bsub -I -app norm") and or variable (dist := "bsub -I -app norm") but both didn't work.

**Comment by laniakea64** [comment]
Depending what else is in your .bashrc, you might be able to use the shell function from your .bashrc -
```
foo:
  . ~/.bashrc && dist ...

shebang:
  #!/bin/bash
  . ~/.bashrc
  dist ...
```

You could also define it directly in a shebang recipe -
```
shebang:
  #!/bin/bash
  dist() {bsub -I -app norm "$@"}
  dist ...
```

If the point is to save repeating the same command multiple times or have it defined in one central place, then instead of a shell function, you could put the command in a variable and have `just` substitute its text -
```
dist := "bsub -I -app norm"

foo:
  {{dist}} ...
```

**Comment by yurivict** [comment]
Thank you for this information.

```{{dist}}``` works.
