### ISSUE TITLE
command does not rerun sub-commands

### ISSUE THREAD

**Issue by rpivo** [casey/just#2102]
Running a command which runs various sub commands unexpectedly skips sub commands which were previously run in the same command.

example: I want to run sub commands `a` and `b` again after having run sub commands `a` `b` and `c`, but the second invocation of `a` and `b` are skipped.

```
all: a b c a b
```

**Comment by casey** [comment]
Thanks for opening this issue! This is actually working as intended. Recipes are only run once in a given invocation of `just`, even if they appear multiple times on the command line, or as dependencies. This is so that multiple recipes can depend on a recipe that performs some kind of setup (for example, building a binary) and even when they all run, that setup will only be performed once.

**Comment by casey** [comment]
I added documentation of this in #2103.
