### ISSUE TITLE
Nushell completions should be added to documentation and `--completions` (if appropriate)

### ISSUE THREAD

**Issue by starthal** [casey/just#2135]
It looks like Nushell completions are available in the release tarball.

Current documentation doesn't mention nu completions, and they can't be "generated" at runtime with `--completions` yet.

The script uses the JSON-parsing invocation suggested in [ #974](https://github.com/casey/just/issues/974#issuecomment-2066236720), as opposed to a Clap v4 approach. Is there more work to do here or is the current script satisfactory?

**Comment by casey** [comment]
Thanks for opening this issue! That's definitely an omission on my part, I never thought about the fact that nushell completions couldn't be generated with the `--completions` subcommand.

Fixed in #2140, which prints the script with `--completions nushell`.

Improvements to the current script are welcome. Clap doesn't have nushell support, so the current script was just written by hand.

**Comment by starthal** [comment]
FYI this is available now with Clap v4: https://crates.io/crates/clap_complete_nushell 

It's maintained by the `clap` maintainer so I'm guessing it's only separate to `clap_complete` for stability reasons.

If you believe it would improve maintainability, I could try a PR. But the current script isn't causing an issue for me.

**Comment by casey** [comment]
The current script doesn't pose any maintenance issues, but it's very limited. I believe it only completes recipe names and nothing else.

It would be great to integrate `clap_complete_nushell`, although the script generated by `clap_complete_nushell` would have to be modified to also complete recipe names. I'll open an issue to track this.

**Comment by casey** [comment]
See #2142.
