### ISSUE TITLE
`set positionnal-arguments` append target at the end of the command on Windows but not on Linux

### ISSUE THREAD

**Issue by aneojgurhem** [casey/just#2146]
Hi !
The title says it all. Here is a justfile to reproduce the issue.

```just
# Enable positional args
set positional-arguments

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
set shell := ["bash", "-c"]

target:
  echo hey
```

On Linux (my wsl) with just version 1.25.2, I get the following result

```
echo hey
hey
```

and on Windows Powershell with just version 1.28.0, I get the following result:

```
echo hey
hey
target
```

Removing `set positional-arguments` make it behave the same way in both Windows and Linux.

Did I understood something wrong ?
Thanks for any help !

**Comment by casey** [comment]
Positional arguments will include the name of the recipe being run before arguments, since bash expects the name of the executable to be the first argument, with arguments afterwards being the actual positional arguments.

So on Windows, I think it's running something like:

```
powershell.exe -NoLogo -Command 'echo hey' target
```

From a bunch of different issues over the years, I think the way powershell handles arguments is super weird, and positional arguments just don't really work with powershell.

I don't know what the best workaround is, or if maybe the best answer is just to document that powershell and positional arguments aren't a good match.

**Comment by aneojgurhem** [comment]
That's exactly what happens !

The issue here is that a perfectly fine script with bash does not work on powershell when positional arguments are enabled. That is very annoying. On our side, we rely on positionnal arguments so we cannot completely disable it. However, when we use powershell, we do not need positionnal arguments. We need it for other recipes.

I can give you a few suggestions:
- allow to set settings from the command line
- allow to use dynamic conditions on settings
- add a setting to remove the file name ($0) from the command sent to shell

Do you think something is doable ?
Thanks!

**Comment by casey** [comment]
We could allow `positional-arguments` to be set from the command line. However, I'm a bit hesitant to make settings which recipes depend on to operate to be set on the command line. I.e., if a setting is obligatory for a recipe to work correctly, it should be set in the justfile, so that it's always set. An argument against this is the fact that the `--shell` and related arguments can be set from the command line.

So maybe the best option is a `[positional-arguments]` attribute which can be set on recipes that require it, so you can put it just on the recipes that require it.

**Comment by aneojgurhem** [comment]
I think that the attribute is a good compromise until powershell is less weird.

**Comment by casey** [comment]
For your use case, would it be better to have an attribute that turns off positional attributes, or one that turns on positional attributes? I.e., do you have more recipes that use positional attributes, or more recipes that use powershell and so will break if you use positional arguments?

**Comment by aneojgurhem** [comment]
It feels more natural to enable it with the addition of the attribute.

**Comment by casey** [comment]
Added a `[positional-arguments]` attribute in #2151!

**Comment by aneojgurhem** [comment]
Great ! Thank you !
