### ISSUE TITLE
Support for remote file

### ISSUE THREAD

**Issue by romanzdk** [casey/just#2171]
I would like to have "company" wide Justfile with ability to override certain tasks on per-project level. I imagine I would put the "master" Justfile into some repository and then in local repository just reference this master one using URL similarly as Taskfile does - https://taskfile.dev/experiments/remote-taskfiles/

**Comment by laniakea64** [comment]
https://github.com/casey/just/issues/1799

> I imagine I would put the "master" Justfile into some repository and then in local repository just reference this master one 

In this case, you could set up your local repository to pull in the repository containing your company-wide justfile as a git submodule.  Then your local justfile can reference the company-wide justfile by relative file path in `import` or `mod`.

**Comment by romanzdk** [comment]
Yeah, aware of that, thanks but I do not find this setup user friendly as we would need to include the submodule in every repository and I do not fancy that. I believe referencing file via url should be fairly straightforward.

**Comment by casey** [comment]
There's currently a pretty decent workaround for this, see the docs I added in #2175. I'm currently not sure I want to support remote justfiles directly, since the workaround is pretty simple, and I'm not entirely sure how caching would work (download once and reuse? always download?).

**Comment by igorgatis** [comment]
This could be an experimental feature. This way people may learn and provide feedback. I'd say leveraging cache related headers are good enough:

![Image](https://github.com/user-attachments/assets/b1bf9e5c-0593-4b77-b4b5-4203a8181102)

**Comment by casey** [comment]
Just a heads up, [just 1.52.0](https://github.com/casey/just/releases/tag/1.52.0) has made using remote justfiles a bit nicer.

You can run recipes that do not depend on absent optional modules, even if you have recipes in the same justfile that do depend on absent optional modules.

This means that this now works:

```just
mod? foo

baz: foo::bar

init:
  wget https://example.com/justfile > foo.just
```

If `foo.just` is missing, you can still run the `init` recipe to fetch it, even though `baz` depends on it, which would previously have been an error.

My hope is that this will make remote justfiles nice to work with, since you can move fetching and updating into a just recipe, instead of an external script.
