### ISSUE TITLE
Comments for modules, and ideas for improvements to groups

### ISSUE THREAD

**Issue by Spatenheinz** [casey/just#2190]
Hey, first of all very nice project.
I am playing a bit around with modules and groups (as kind of a seeing if i can make them play together nicely and I have seen a few places where I have some suggestions).
Firstly I define the following files:

```
# Justfile

# contains a list of recipes
mod foo

[group('lint')]
rust-lint:
    echo 'Running Rust linter…'

# not in any group
email-everyone:
    echo 'Sending mass email…'
    
# foo.just

[group('rust recipes')]
build_rust_recipes:
    echo "building rust recipes"
```

when i do `just --list` i get something along the lines of `foo ...`, It might be relevant to allow for the comment above `mod foo` to be added to the `--list` view. I also see that there is support for showing nested modules, which I think is great. I think it similarly could be useful if it was possible to list all recipes for a certain group e.g. doing `just --groups lint` would show every recipe under the group.
The actual syntax could differ (but covey meaning similar to a REST API or similar), but would ensure that for instance that groups and modules were not conflicting as it would if one chose to use `just --list <name_of_group>`.

Lastly I see that groups from modules are not included in `--groups`. Which could also be useful.

Maybe this issue should be split into different ones addressing each problem?

If these changes are welcome then I would very much like to participate and come up with a proposal and do a PR.

**Comment by casey** [comment]
- I think doc-comments for modules would be great. Could you open a separate issue for it?
- Listing groups would be great. Currently, `just --list` takes an argument which is a module path, so the syntax may have to be different, i.e, it may have to have some kind of distinguishing syntax to list groups, like `just --list @GROUP_NAME` or something. Can you open an issue for this?
- I'm not sure if groups from submodules should be included in `--groups`, since recipes in submodules aren't included in `just --list`, but why don't you open an issue for it anyways, at least to collect feedback and brainstorm.
