### ISSUE TITLE
Allow expressions in `[confirm: …]` attribute

### ISSUE THREAD

**Issue by alerque** [casey/just#2287]
Based on the docs and some tests it doesn't seem possible to use variable substitutions in confirm messages. I would have expected something like this to work:

```just
[confirm("Really do stuff with {{arg}}?")]
action arg:
	@echo Doing stuff with {{arg}}
```
But it doesn't:

```console
$ just action foo
Really do stuff with {{arg}}? y
Doing stuff with foo
```

**Comment by casey** [comment]
`{{…}}` interpolations aren't processed in strings. See #11.

But the issue is still valid, since you can't do:

```just
[confirm("Really do stuff with " + arg + "?")]
action arg:
	@echo Doing stuff with {{arg}}
```

Changing this would require accepting an expression in the confirm attribute, and evaluating it. This is a somewhat involved change, since then the evaluator needs to evaluate expressions inside of attributes, but I think it's reasonable.

**Comment by laniakea64** [comment]
Close in favor of https://github.com/casey/just/issues/2521 ?

**Comment by casey** [comment]
Yup, thanks!
