### ISSUE TITLE
just submodule -l

### ISSUE THREAD

**Issue by anacrolix** [casey/just#2332]
Passing -l after naming a submodule doesn't work. It sort of makes sense but it's unexpected.
```
> just sqlite -l
error: Justfile does not contain recipe `sqlite -l`.
```
Where there's a justfile in my current directory, and one in `sqlite/`. The current one contains:
```
mod sqlite
```
I can do `just -l sqlite`.

**Comment by casey** [comment]
Since you could have a recipe named `sqlite` which takes an argument, I think there's not a reasonable way to get this to work. Once `just` sees the first positional argument (i.e., not a flag or option) it will parse the rest of the arguments as recipe names and arguments.

**Comment by anacrolix** [comment]
After it sees a submodule name, there's no reason to expect a recipe name, in fact a recipe named `-l` seems a bit odd.

**Comment by casey** [comment]
There are other issues here. The `justfile` is only ever even parsed after command line parsing is completed. So in order to know it's a submodule, you need to parse the command line, however, once you parse the command line, it would be impractical to go back and re-interpret additional arguments after a submodule.
