### ISSUE TITLE
Just enters infinite loop if it calls just on non-existant justfile

### ISSUE THREAD

**Issue by fuine** [casey/just#236]
Steps to reproduce:
```sh
mkdir just_test && cd just_test
mkdir a
echo -e "build:\n    @echo 'top-level justfile'\n    @just a/" > justfile
echo -e "build:\n    @echo 'a/ justfile'" > a/justfile
just
# So far everything should be working correctly
rm a/justfile
# This loops infinitely
just
```

**Comment by casey** [comment]
Thanks for the report!

Hmm, this is an interesting one. When `just` gets an argument with a slash in it, as in `just a/`, it starts its search for a justfile in that directory. Since it looks from that directory up, in this case it finds the justfile in `just_test` (which is the current justfile), executes the default recipe, and thus enters an infinite loop.

We could change it to only look for a justfile in the directory passed as an argument, and not search upward. However, I'm not sure if that's the right behavior.

For example, if we have:

```
project/
  justfile # with recipe project-recipe
  foo/bar/justfile
```

If one is in `bar`, and one wants to run something in the project justfile, one would need to type `just ../../project-recipe`, which would be annoying.

We could special case it so that `..` was special, and it would look upwards in case of a `..`, but not otherwise, but I'm not sure it's worth the benefit.

Thoughts?

**Comment by casey** [comment]
I think I'm going to close this as working-as-intended-ish. It's strange behavior, but I don't think there's an elegant fix.
