### ISSUE TITLE
Manual links are unstable

### ISSUE THREAD

**Issue by tomodachi94** [casey/just#2368]
Hello!

Unfortunately, links to the manual are unstable and sometimes change.

For example, before https://github.com/casey/just/pull/1316, https://just.systems/man/en/chapter_18.html was a link to the section called "Other Editors", but it now links to "Micro". This happened in https://github.com/quotidian-ennui/quotidian-ennui.github.io/pull/11, for example.

Thank you for this awesome project :heart:

**Comment by casey** [comment]
Ahh, that's annoying. I'm not sure it can be fixed though, since the docs are generated by mdbook, which uses chapter numbers instead of names in URLs. One thing you might try is linking directly to the readme. It has the same content, but the  fragment links are based on the heading, and so should be more stable. For example:

https://github.com/casey/just?tab=readme-ov-file#other-editors

**Comment by laniakea64** [comment]
> I'm not sure it can be fixed though, since the docs are generated by mdbook, which uses chapter numbers instead of names in URLs.

But other sites generated with `mdbook` don't have this issue, e.g. https://rust-lang.github.io/mdBook/ and https://gtk-rs.org/gtk4-rs/stable/latest/book/
How are they solving it?

Could this issue with just.systems actually stemming from code in https://github.com/casey/just/tree/master/crates/generate-book ?

**Comment by casey** [comment]
Whoops, you're totally right! Let me see if I can fix that.

**Comment by tomodachi94** [comment]
Maybe it could be as simple as replacing calls to `number` with calls to `slug`?

https://github.com/casey/just/blob/a440a6ac52349059677c04827e19f6dbe9639898/crates/generate-book/src/main.rs#L79

**Comment by casey** [comment]
Fixed in #2372! I can't probably that they'll be permanently stable, since chapter titles can still change, but they should be much more stable.
