### ISSUE TITLE
Extended API for background process runner

### ISSUE THREAD

**Issue by pka** [casey/just#2389]
I'm using Just for data processing with shell or Python scripts. Since they can take a long time, I currently run them in the background with `screen` or a workflow engine.
I couldn't find a lightweight background runner somewhere between [Pueue](https://github.com/Nukesor/pueue/blob/main/README.md) and [PM2](https://github.com/Unitech/pm2/blob/master/README.md). So I wrote a prototype (~500 loc and few dependencies):

![screencast](https://github.com/user-attachments/assets/354eb73b-e160-42c9-be5d-05cfc0a07bdd)

Now I would like to integrate it more tightly into just. The goal would be that no additional configuration is needed to run Just recipes in the background, similar to docker-compose. This would require an extended Just API (see also #365), but even then, adding additional attributes like `[cron */5 * * * * *]` is probably out of scope for an API?

**Comment by casey** [comment]
Yah, I think adding user-visible features to `just` which are only useful for using `just` as a library is out of scope. You could try putting annotations in doc comments, which is a little gross, but would get the job done.

**Comment by pka** [comment]
I think using existing attributes like `[group('autostart')]` or `[script('at 5 PM')]` could already do the job. So only the wish for an extended API remains. Would it be feasible to publish roughly the same API as the chooser uses?

**Comment by casey** [comment]
What API would be required?

**Comment by pka** [comment]
A minimal API would probably be along this:
* `pub struct Config;`
* `Justfile::load(config: &Config) -> Result<Justfile>`
* `Justfile::public_recipes(&self, config: &Config) -> Vec<Recipe>`
* `Justfile::run_recipe(&self, config: &Config, recipe: &Recipe, positional: &[String]) -> Result<(), i32>`
* `Recipe::executor(&self) -> Executor`
* `Recipe::group(&self) -> Option<String>`

**Comment by casey** [comment]
This is actually a bit tricky. The `Config` transitively contains a whole bunch of currently private structs, which would have to become public. Also, this signature `Justfile::load(config: &Config) -> Result<Justfile>` isn't easily possible, since a `Justfile` borrows from a `Loader` which is responsible for loading source files. And, just kind of thinking out loud here, the `just` crate's version is used for the `just` binary, whereas a `just` library crate would want to have its own version number, since it would likely have frequent breaking changes, at least at first. Ideally, a standalone `just` library crate would actually start at a `0.x.x` version, so that breaking changes could be made without having to bump the major version. I think it would be ideal to have a `justfile` crate which was a library crate, so it could have its own version.

I'm not feeling suuuper up to the task at the moment, but I could see all this eventually happening.
