### ISSUE TITLE
Add "--update" command

### ISSUE THREAD

**Issue by GammaGames** [casey/just#2401]
If just is installed with a package manager, it would be nice to be able to run `just --update` to have it run the correct update command. There's already a `--changelog` command, so I think it wouldn't be out of place

**Comment by casey** [comment]
I'm thought about this a bit, and I think this is just impossible to do well. You would have to use a bunch of fragile heuristics to figure out which package manager `just` was installed with which would break if anything wasn't the default. This plus the fact that it only saves the user from having to run one command, which they probably know (since they installed `just` using their package manager in the first place) makes me feel that the juice isn't worth the squeeze.

**Comment by GammaGames** [comment]
That makes sense, thanks for your consideration!
