### ISSUE TITLE
Windows path backslashes removed from command args

### ISSUE THREAD

**Issue by cedws** [casey/just#2467]
I'm on Windows and would like to pass a Windows-style path with backslashes to a program like so:

```
echo *args:
    echo {{ args }}
```

When I invoke this target like so, the backslashes are removed making the path incorrect:

```
$ just echo "E:\\test"
echo E:\\test
E:test
````

I thought PowerShell could also be the culprit, but invoking `echo` directly works as expected:

```
$ echo "E:\\test"
E:\\test
```

Just version: `just 1.36.0`

**Comment by laniakea64** [comment]
> When I invoke this target like so, the backslashes are removed making the path incorrect:
> 
> ```
> $ just echo "E:\\test"
> echo E:\\test
> E:test
> ```

I'm not familiar with Windows/PowerShell, but maybe this output might be showing what's happening? -

The `args` recipe parameter is not a list of arguments.  It's a single string containing all received arguments separated by spaces - https://just.systems/man/en/recipe-parameters.html
So for example `just echo "E:\\test" "E:\\testing 1 2 3"` would invoke `echo` recipe with `args` parameter set to `E:\\test E:\\testing 1 2 3`, so the command in the recipe body would become literally `echo E:\\test E:\\testing 1 2 3`.

To find out whether this is the actual issue:
- What happens if you run `echo E:\\test` (without quoting) directly in PowerShell?
- Does it help to use [`[positional-arguments]` recipe attribute](https://just.systems/man/en/attributes.html) and instead of using the `args` parameter in the recipe body, use the PowerShell equivalent of `bash`'s `"$@"` syntax?

**Comment by casey** [comment]
With this recipe:

```
echo *args:
    echo {{ args }}
```

The command line `just echo "E:\\test"` runs `echo E:\test` in the shell. Since `\` introduces an escape sequence, in this case `\t`, it needs to be quoted, so the recipe should be:

```
echo *args:
    echo '{{ args }}'
```

This is problematic, because `args` should be passed as multiple args. So in this case I think @laniakea64 suggestion to use positional arguments is the right way to go:

```
set positional-arguments

echo *args:
    echo "$@"
```

**Comment by cedws** [comment]
Works, thank you.
