### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by casey** [casey/just#3]
It would be really nice to support Windows users. However, `just` currently calls `sh` explicitly, which isn't available on Windows.

Some ideas:
1. Use the `sh` provided by the ubuntu subsystem in Windows 10
2. Allow using cmd.exe or powershell on windows
3. Write a `sh` in rust that runs on every platform

3 is probably the best solution, but also the most work.

**Comment by casey** [comment]
This could be supported with a "shlex" function like python's. It wouldn't do much but it would probably work for 90% of cases.

**Comment by casey** [comment]
It looks like `cmd.exe /c COMMAND` is the way to run arbitrary commands on windows.

**Comment by casey** [comment]
The main thing stopping me from adding windows support at the moment is that I would have no way to test it, since I don't know how to spin up a windows VM, install rust, install just, and test.

**Comment by casey** [comment]
[AppVeyor](https://www.appveyor.com) is the way to go for windows CI.

**Comment by casey** [comment]
Whoops, didn't mean to close.

**Comment by Meralis40** [comment]
Hello,
I started a fork when I've succeeded into running just on Windows : https://github.com/Meralis40/just
But there are the following :
- justfile must be with `'\n'` only, but standard on Windows is `"\r\n"`
- sh must be on path

I've just tested basic commands, like running `just build` and `just check` on just directory.
It can be a workaround until #161 is resolved. What do you think ?

**Comment by casey** [comment]
Hi @Meralis40!

Sorry for not responding earlier. I think that your fork looks reasonable. The justfile grammar can be modified to accept `\n` or `\r\n`.

Have you tried running the tests? I think that some of them may have unixisms in them, but they can probably be fixed.

What version of `sh` are you testing with?

I want to merge your code, but I need to set up a windows environment set up so I can build and test it, and I'm not sure when I'll be able to get to that.

**Comment by Meralis40** [comment]
For the `sh` version I'm testing, I'm using the `bash` provided with GitHub Desktop (v4.3.46). It's one build with MSys.
For the tests, I've just made a new commit who fix a lot of them, because of exit code (on Windows, we have `-1` and not `255`).
10 tests keeps failing, it's in this document : https://github.com/Meralis40/just/blob/master/failing_tests_windows.txt
Some on them are because of shebang, not supported on Windows.

**Comment by casey** [comment]
Hmm, pretty interesting. I'm guessing that a lot of windows users will have `sh` on their path from their git installation, so depending on that will be good enough for v1 of windows support.

I got cracking on this in the windows branch:
https://github.com/casey/just/tree/windows

I based a lot of the changes on the code that you uploaded to your branch, I hope that's okay.

I expect to finish some time this week, or this weekend at the latest.

**Comment by Meralis40** [comment]
It's ok, the work I've done was more for trying to get a basic version of just in Windows.
I will test it when I can.

**Comment by casey** [comment]
Finally fixed with a series of changes, ending with #189 

Thanks for getting the ball rolling, @Meralis40!

I've tested things under github desktop for windows and git bash, and it should work under cygwin as well.

It uses the `cygpath` utility to translate the path to the interpreter in shebang paths and construct an equivalent command, so shebangs should work.

@Meralis40: You mentioned an issue with `\r\n` line endings, but I didn't run into problems with them. Did I perhaps miss a case?

**Comment by casey** [comment]
Closing this issue since everything should be working. I'm going to set up continuous integration on windows with appveyor so that things don't break going forward.

**Comment by runeimp** [comment]
In Windows 10 Pro with `just v0.3.5` I get

```bash
error: Unknown start of token:
  |
1 | #
  | ^
```

This only happens when the file is using `CRLF` instead of just `LF`. This suggests that `just` is currently not `EOL` agnostic.

To some give context, the _Justfile_ is being created on macOS 10.12.6. But in Git BASH on Windows there is an automatic conversion from `LF` to `CRLF`. If I make changes and commit back the default is to convert the file back to `LF` when pushed to a remote server, if I'm not mistaken. That can be disabled but it is the default as I understand it.

You can double-check, and change to and from, different line endings using Notepad++ on Windows.
