### ISSUE TITLE
Filesystem Watcher

### ISSUE THREAD

**Issue by myrrlyn** [casey/just#301]
Having used tools such as `cargo-watch` on my Rust projects, `sass --watch` on my Sass projects, `middleman serve` on my website project, and IDEs with compile-on-save functionality, I am a firm believer in executing tasks on filesystem events.

Would `just` be interested in gaining an integrated `watch` subcommand, invoked as

```sh
just watch [args]
```

as a complement to

```sh
just [args]
```

which has the exact same parsing and behavior as normal operation, only `just` stays alive and executes the command again whenever it sees a filesystem event?

----

[watchexec](https://github.com/mattgreen/watchexec) works on Linux, macOS, and Windows, and I *believe* (I haven't looked in a while) is able to use OS-provided notification APIs for each rather than polling for updates every second or so.

If this is functionality in which you'd be interested, I'm willing to add it and submit a PR.

----

Potential bikeshedding:

- if a `Justfile` task named `watch` exists, what does `just watch` entail?

    I am of the opinion that this should execute the `watch` task from `Justfile` once.

- what mechanisms should `just` use to filter notification events?

    I would imagine the `ignore` crate by default, with options for overriding it on the command-line or in the `Justfile`?

- "just have your tasks call [`watchexec`](https://github.com/mattgreen/watchexec) or similar"

    fair point

**Comment by casey** [comment]
I like this idea, although I'm not sure it's a good idea to integrate it into `just` directly.

I checked out `watchexec` (which looks awesome, by the way) and it provides a ton of options for customizing which files to watch, and what action should happen when those files changes.

There are about 13 such options, and it seems like it might be confusing to add all of them to `just` itself.

Also, if a user wants to watch a complex set of files for changes, this might be a pretty hefty command line, and thus the user might be better of creating a recipe like `watch-test` that calls `watchexec --exts rs just test`, instead of having to type `just -w --exts rs test` as a command.

So overall, I think that pointing users to `watchexec` itself is probably a good idea.

Maybe it would be a good idea to dedicate a section of the readme to other tools, like `watchexec`, that complement `just`?

**Comment by kdar** [comment]
My personal opinion is this is better left to outside tools.

**Comment by casey** [comment]
I think I agree that this is best left to outside tools. I added a pointer to the readme though, since I think that it's definitely a userful thing for just users to know about.
