### ISSUE TITLE
Could just be included with Cargo?

### ISSUE THREAD

**Issue by casey** [casey/just#322]
I've been thinking about this for a while! `just` is a nice tool, but a major shortcoming when compared to `make` is that it isn't installed on every unix machine by default. Having to install Yet Another Tool is annoying, even if it's a useful one.

This could be solved, at least for Rust users, if `just` were included with Cargo. I think this would be good for the Rust ecosystem in general, since, at least [anecdotally](https://www.reddit.com/r/rust/comments/70b74a/commandline_tools_written_in_rust/dn1z9wn/), justfiles are helpful when figuring out how to work on a project written by someone else. If `just` were included in the default distribution, then more users would write justfiles for their rust projects, which would lower the barrier to entry in the rust ecosystem in general, and serve as an additional form of documentation for rust projects.

Some thoughts:

- Rust's Tier-1 platforms include MacOS, Windows-GNU, Windows-MSVC, and Linux-GNU in 32-bit and 64-bit flavors. Just works on these platforms, but depends on having a working `sh`, which means that Windows users also need to install cygwin, git-bash, or the GitHub shell. I don't have a great answer for how to make Windows a first-class citizen.

- I think the function of a file called `Justfile` is not obvious, so making the name `Commands` might be better, possibly also changing the name of the command to something else.

- I would feel a lot more comfortable tackling this project with the help of someone who was familiar with the RFC process.

- Similarly, it would be nice to have help with someone who was a pure windows developer, to make sure those users are well supported.

- Rust and Cargo have very strong backwards compatibility guarantees, so syntax for future features should be reserved in advance, and features that might go away should be removed.

**Comment by bugabinga** [comment]
Hi!
Some thoughts in response:

- The dependence on `sh` is a real problem. It is hard to explain the value proposition of _just_ over plain shell files, if _just_ is not cross-platform.
- The name `Justfile` is a play on `Makefile`. It communicates something to people already familiar with _just_ or _make_. A more accessible approach could be to have a `COMMANDS[.md]` file. Imagine a "literal programming style", marked up `Justfile`. Maybe even directly in the `README[.md]`.
- I think it is problematic to expect _Cargo_ to adopt a tool with yet another syntax. For Rust beginners, it is hard enough being confronted with Rust/Toml/Shell, which is the minimum necessary today. An approach like [cargo-make](https://github.com/sagiegurari/cargo-make) might make more sense here. However, I like that _just_ is __not tied to Cargo__. It is generally useful.


Fundamentally, this issue comes down to _bootstrapping_.
How does one get _just_ for the first time?
I imagine it being about solving the following scenario:

1. Install fresh OS
2. Install _git_
3. Clone some repo that uses _just_
4. Now what ?

`Gradle` for example, can bootstrap itself, if the repo maintainer uses a command called `gradle wrapper`.
That produces a shell/batch `./gradlew` script that downloads the specified version of gradle locally into a `.gradle` folder in the repo.
Subsequent calls to the script launch the local copy of gradle.
Maintainers then encourage the use of `./gradlew` in their documentation.

This solution solves 2 problems.

1. Bootstraping the toolchain.
2. Keeping contributors on the same version of the toolchain.

The downsides are more overhead for contributors (20 clones using _just_ could mean 21 copies of _just_ on disk), and hard to write/maintain bootstrap scripts.
Take a look at [an example gradlew script for unix](https://github.com/evant/gradle-retrolambda/blob/master/gradlew).
Keep in mind, that the scope of _gradle_ (Java build tool) allows them to assume a preinstalled JVM.
_just_ could either pull precompiled binaries or need to install the rust toolchain and compile in the worst case.

**Comment by nathanielknight** [comment]
My gut feeling is that the functionality would too close to [build.rs](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to be added to the base system. For what it's worth, once Cargo is installed, installing `just` is a one-liner: [`cargo install just`](https://doc.rust-lang.org/book/second-edition/ch14-04-installing-binaries.html).

That said, I do use Rust on Windows quite a bit, and while I'm by no means a Windows expert I'm happy to be a test user.

**Comment by joshuawarner32** [comment]
My perspective: I recently introduced a `justfile` into my team's private repo, with the intent of replacing a bunch of bash aliases people had shared ad-hoc.  Response has been positive so far, but it remains to be seen whether it'll "stick".

@bugabinga, regarding the `sh` dependency: for me, the value prop of a `justfile` over a bunch of shell scripts is three-fold:
* It's in one place, rather than scattered around a bunch of files
* `Just` gets some important defaults "right" - such as setting the working directory to the dir of the `justfile`, rather than shell scripts where you have to _remember_ to do that in each script.  In my experience, if the standard workflow _doesn't_ do that, things tend to become brittle over time and slowly the recommended workflow turns into "cd into the root first, then run that command - that's why you're running into that obscure error".  On a large team, not having to worry about that problem is worth a lot.
* A `justfile` has a much cleaner syntax than trying to e.g. write one shell script that has a bunch of functions that it conditionally executes based on the first argument.

That said, I 100% agree that not _always_ depending on `sh` would be really useful for onboarding windows users in a project.

**Comment by casey** [comment]
@bugabinga, @neganp, and @joshuawarner32,  thank you for your feedback!

I think the first step is going to be to have a compelling story for `just` on windows that doesn't require installing `sh`. It should be possible for windows users to write their entire justfile with recipes that use `cmd.exe` for recipe command execution. I an issue, #326, for this.

The basic idea is to allow users to indicate, probably by titling the justfile, `justfile.batch`, that they want their recipes to be executed by `cmd.exe`. Another interesting possibility is allowing them to title their justfiles `justfile.ps1`, to use powershell for recipes.

**Comment by casey** [comment]
I think it's unlikely that this will happen any time soon, so I'm going to go ahead and close this issue.
