### ISSUE TITLE
Any plan to add ssh support?

### ISSUE THREAD

**Issue by linux-china** [casey/just#358]
justfile as following:
```
check[root@xxxx:/tmp/, root@yyyy:/tmp/]:
   ls

check2[root@xxxx:/tmp/]:
   #!/usr/bin/env python3
   print('Hello from python!')
```

**Comment by casey** [comment]
This would definitely be cool! I worry though that if the feature is built into just itself, it wouldn't be sufficiently flexible for most use cases. For example, how would it select the right SSH program and options?

I think that rather than adding this, it would be interesting to think about some kind of more general recipe decoration mechanism that would support ssh.

One idea for a quick fix is to create a script which does things over SSH, and use that in a recipe shebang line, like so:

```
check:
  #!/usr/bin/ssh-wrapper root@xxxx:/tmp/
  ls
```

This would be annoying, but it would allow you to do roughly what you want.

**Comment by linux-china** [comment]
Now if you want to execute commands by SSH on remote host, lots of works to do. set up working directory,  bash login, use shebang etc. If just with SSH support by default, and it will be amazing.
Now I use following script to execute commands on remote servers.

```
remote:
   #!/usr/bin/env bash
   ssh ubuntu@xxxx.com 'bash -l -s' <<'ENDSSH'
     ls
     ls /home
   ENDSSH
```
Anybody uses different way to make remote commands execute easy?

**Comment by casey** [comment]
That's really cool! I wouldn't have thought to use here docs that way.

**Comment by casey** [comment]
I think the right way to do this is with an annotation. However, it's not obvious to me what a reasonable annotation would be that could accomplish this.

One possible approach is a `shell` annotation which overrides the shell for an individual recipe:

```
#[shell("ssh", "ubuntu@xxxx.com")]
remote:
  hostname
  ls ~
```

This would work and would be a good first step, since it's very similar to the contemplated `set shell := [...]` construct.

However, it is not ideal to `ssh` for every line of the recipe.

An alternative would be an annotation which said "the contents of this recipe should be passed as an argument to this command" or "the contents of this recipe should be passed on standard input to this command", but those are pretty weird.

**Comment by mihaigalos** [comment]
Discussion thread: https://github.com/casey/just/discussions/1267.

**Comment by mihaigalos** [comment]
> I think the right way to do this is with an annotation.

Thoughts:
* lack of support for multiple hosts.
* lack of support for different users for each of the hosts.

**Comment by casey** [comment]
I think the best way to do this is with an example recipe in the [example directory](https://github.com/casey/just/tree/master/examples). That way, users can copy the recipe into their own justfiles, and customize everything how they see fit.

**Comment by casey** [comment]
I think I'm probably not going to add explicit ssh support. It seems like it would be quite hard to get right.

**Comment by casey** [comment]
Just a heads up, [just 1.52.0](https://github.com/casey/just/releases/tag/1.52.0) has made using remote justfiles a bit nicer.

You can run recipes that do not depend on absent optional modules, even if you have recipes in the same justfile that do depend on absent optional modules.

This means that this now works:

```just
mod? foo

baz: foo::bar

init:
  wget https://example.com/justfile > foo.just
```

If `foo.just` is missing, you can still run the `init` recipe to fetch it, even though `baz` depends on it, which would previously have been an error.

My hope is that this will make remote justfiles nice to work with, since you can move fetching and updating into a just recipe, instead of an external script.
