### ISSUE TITLE
Unsafe unwrap in parser

### ISSUE THREAD

**Issue by RadicalZephyr** [casey/just#363]
Found with the new fuzz testing setup!

This input `export\x09AA` causes the Lexer to fail.

```rust
extern crate just;

fn lex_and_parse<'a>(input: &'a str) -> Result<(), just::CompilationError<'a>> {
  let tokens = just::Lexer::lex(input)?;
  let parser = just::Parser::new(input, tokens);
  let _justfile = parser.justfile()?;
  Ok(())
}

fn main() {
  let input = "export	AA";
  lex_and_parse(&input);
}
```

**Comment by casey** [comment]
Awesome, nice find!

The parser uses an itertools adapter that allows putting items back into an iterator. However, if you put back two items in a row, it overwrites the previous item. The bug was caused by removing and putting back an `Eof` token, and then putting back another token, overwriting the `Eof` token. The parser assumes that it will never advance past the last token, but since the `Eof` token was overwritten, it does so and crashes.

**Comment by casey** [comment]
I'm surprised that nobody ever hit this organically!
