### ISSUE TITLE
`just` could not find `sh`

### ISSUE THREAD

**Issue by Kaperstone** [casey/just#430]
I am using Windows 10 and have tried cargo, scoop and the binaries on the releases page, yet, have encountered the same issue in each of those approaches
```
error: Recipe `echo` could not be run because just could not find `sh`: The system cannot find the file specified. (os error 2)
```
The readme.md does not specify any requirements to what I see and I checked the folders, and I am definitely trying to run the .exe files.

What I am trying to do:
I installed a fresh `just` package
my `justfile`
```yaml
echo:
    echo test
````
what I type
```
just echo
```
yet, it gives the error above.

So am I missing something?

P.S. searched the issues tab, haven't found any similar issue except for this issue #161 
EDIT: Found #412 But it isn't the same

**Comment by Kaperstone** [comment]
Okay, so I've come with a workaround for this:
My ``justfile``
```
echo:
    cmd /C echo test
```
can be ran if --shell is specified
```
just --shell=cmd echo
```
typing the options (e.g. `--shell`) after, will cause `just` to think the option is a recipe and will return that it cannot run it.

Is there is a simpler way? like, without specifying the --shell everytime?

**Comment by casey** [comment]
Hi @Kaperstone, sorry that you're running into issues! Just tries to run recipes with `sh`, you can get from Git for Windows, GitHub Desktop, or Cygwin.

The links are at the beginning of the Installation section, but are easy to miss since the information isn't repeated in the subsections that actually contain installation instructions.

The `--shell` flag doesn't work very well, and it's going to be deprecated in its current form.

There's actually an open issue to improve the situation, namely #326. Two improvements are looming on the horizon:

1. Just will start shipping with busybox, so you won't need to supply your own copy of `sh`. This will make things Just Work™ on Windows.

2. Just will get justfile-wide settings, so you can do `set shell := ["cmd.exe", "/c"]` at the top of your justfile. This will allow windows users to, if they wish, opt-in to using `cmd.exe` or Powershell instead of `sh`

I can't give an ETA these, unfortunately, but I'm hoping we'll get there soon. I'm going to leave this issue open so others who run into the same problem can find it.

**Comment by casey** [comment]
Closing, see #326.
