### ISSUE TITLE
string-type recipe arguments that contain spaces are treated as multiple arguments?

### ISSUE THREAD

**Issue by slmjkdbtl** [casey/just#447]
steps to reproduce:
```sh
# test.sh
echo $#
```

```make
# justfile
test +args:
    sh test.sh {{args}}
```

running:
```sh
$ just test one two "three four"
4
```
expected 3 ("three four" as one thing)

**Comment by runeimp** [comment]
Hello @slmjkdbtl you are experiencing two levels of string expansion. This actually has little to do with `just`.  Your initial args are likely coming through as you expect with the "three four" as a string with the space in tact as part of the string. But the quotes themselves are not present when the  `{{args}}` expands the arguments for `test.sh`.

So `sh test.sh {{args}}` expands to `sh test.sh one two three four` (as it should in this context) instead of `sh test.sh one two "three four"`. To fix this try adding a second set of quotes.

```bash
$ just test one two "'three four'"
```
This will result in `sh test.sh one two 'three four'` so that after `sh` does it's round of expansion the script `test.sh` will receive 3 arguments instead of four.

**Comment by slmjkdbtl** [comment]
Thanks @runeimp ! 

I see why the quotes didn't get expanded, and adding a double set of quotes is definitely a valid workaround.
