### ISSUE TITLE
Consider requiring a statement in justfile to load .env file

### ISSUE THREAD

**Issue by casey** [casey/just#469]
If you're here because of a warning, sorry for the inconvenience!

When `just` 1.0 is released, it will stop loading `.env` files by default. Automatically loading `.env` files seemed like it might lead to unexpected behavior, especially because `.env` files are often sitting around, and might be present locally but not present in production, or vice-versa.

In order to avoid unexpected breakages, `just` will issue a warning if a `.env` file is found, but `dotenv-load`, the setting that controls `.env` file loading, is not set. `dotenv-load` currently defaults to `true`, but will be changed to default to `false`.

To silence the warning and continue to load `.env` files, add the following to your justfile:

```
set dotenv-load := true
```

To silence the warning and no longer load `.env` files, add the following to your justfile:

```
set dotenv-load := false
```

You can also suppress the warning by seting the environment variable `JUST_SUPPRESS_DOTENV_LOAD_WARNING` to `1`.

In order to give users plenty of time to update, the change will be made over multiple releases:

- [x] `2021-03-28 v0.8.7` – Add `dotenv-load` setting
- [x] `2021-07-28 v0.x.y` – Warn if `.env` file loaded without `dotenv-load` being set.
- [x] `2022-02-01 v1.0.0` – Change `dotenv-load` default to `false`.

---

This is probably a non-issue. But it strikes me that some users might be surprised when `just` loads their `.env` file. It might be wise to not load `.env` files by default, and let users opt-in with a setting, like so:

```
set load-dotenv := true
``` 

Of course, that would be a breaking change, so it's probably not worth it.

_Update:_ I more and more think there's a bit too much magic and potential for unexpected behavior with automatic `.env` file loading, so I'm more leaning towards doing this.

I'd like to let users control:

1. Whether or not a dotenv file is loaded at all
2. The name of the dotenv file
3. Whether or not to search recursively up to the root for the dotenv file

Eventually, I'd like the default behavior to be to not load a dotenv file, unless the user asks for it with a setting in their justfile, or a command line argument.

In order to avoid disruption, we can have a transitionary period during which Just will emit a warning if it finds a `.env` file but there was no directive in the Justfile,  suggesting that the user add a directive to load the `.env` file.

I'm eager to hear from people who would be annoyed by this change, i.e who would now have to write a statement to load a `.env` file.

As for the actual way of controlling these settings, here's an idea. Dotenv loading would be controlled by the following settings, shown with their default settings:

```
# control whether or not to load a dotenv file at all. defaults to `false`, so no dotenv file is loaded by default
set dotenv-load := false

# controls the file name of the dotenv file. defaults to `.env`
set dotenv-name := ".env"

# controls whether or not to search parent directories recursively, up to the root, defaults to `true`
set dotenv-recursive := true
```

I'm not sure whether `dotenv-recursive` should be true or false by default. We should probably do whatever other dotenv implementations do by default.

As an additional convenience, if `dotenv-name` or `dotenv-recursive` are set in a justfile, `dotenv-load` will also be set to to `true`, if it isn't set explicitly to `false`.

**Comment by runeimp** [comment]
I've just ran into a use case for this. Specifically though I'd like a way to disable the inclusion of the `.env` variables on a per recipe way. That would be very useful for me with certain projects. I could see a major benefit in a global option as well. Actually an environment variable to control it would be quite nice. Something like `JUST_DOTENV=ignore` could solve the system usage problem and

```bash
$ JUST_DOTENV=ignore just recipe-name
```
Would work for temporary use cases. It's usage could even be expanded to use other files for just's environment like `JUST_DOTENV=.just-env` or some such.

**Comment by casey** [comment]
I'd definitely be open to turning it on or off on a per-recipe basis, although that would probably require a mechanism for annotating individual recipes, which doesn't exist yet.

I'd be slightly worried about using an environment variable to turn off `.env` loading, since that might have unintended consequences if `just` is invoked recursively.

However, it would be very easy to add a command-line flag that would turn off `.env` loading, for example `just --load-dotenv false` / `just --no-dotenv` or `just --dotenv SOME_OTHER_FILE`.

Would that work?

Also, it would be super helpful if you could detail the use cases that make turning off `.env` loading on a per-recipe and one-off basis useful, so I can understand how the feature would be used.

**Comment by runeimp** [comment]
Those options would ultimately work for me but partially defeat the purpose of using I believe. The use case was with my [Templar](https://github.com/runeimp/templar) app (and potentially other apps that use `.env` as well run from `just`) that uses environment variables (including those that are present in a local `.env` file) as one of the data sources it can use to populate a template when rendering. Trying to run tests where Templar is told to ignore `.env` files but still use environment variables is tough when the command runner is already populating the environment with the values from the `.env` file that Templar is being run within. 👼

**Comment by casey** [comment]
Gotcha, I think I understand. And it wouldn't work to have a way to disable loading `.env` files for the entire justfile? Like:

```make
set load-dotenv := false

# rest of the justfile
```

**Comment by runeimp** [comment]
Sorry, thought I'd already responded to this last question. 👼

I believe the ability to disable `.env` for the entire Justfile would be fine in my case with my [Templar](https://github.com/runeimp/templar) project. Though I could see it being not the best way for other potential projects. Though if #460 happens it's probably a moot point.

**Comment by ngirard** [comment]
I wish to suggest the following:
- running `just` does not load any env file;
- running `just -E|--envfile` loads the env file named `.env` in the current directory, if it exists;
- running `just --envfile=<path>` loads the env file named `path`.

I'm aware it is a breaking change ; but in return:
- it makes the behavior of the default invocation more predictable and simpler to comprehend ;
- it allows to load an env file whose name doesnt start with a dot, hence is visible via `ls`, which is preferable in some scenarios ;
- it allows to load values from different files, corresponding to different profiles (which is something I've been missing several times with Just) (and solves #460 );
- all with a single, consistent syntax.

What do you guys think ?

**Comment by runeimp** [comment]
While I agree that would be the most obvious way to go about things in a general sense I disagree in the context of typical `.env` file usage. The typical usage is that most tools that recognize a `.env` file use them automatically (in my experience) as they are usually part of the overall configuration of a project. And `just` is (in my experience) a tool used to facilitate project management. So if your working on a project that is (in general) has many parts or it's main part configured by environment variables or a `.env` file when present then tools like `just` should be able to benefit from that configuration automatically as well. The expectation (in my experience) is that I often need to create my own `.env` for a project to align it with my system's setup and that most if not all tools that are part of that project will respond to the presence of that `.env` file. And those that I don't want to use the `.env` file need to be told to ignore it when that is necessary. Typically for testing purposes.

**Comment by ngirard** [comment]
@runeimp, thanks for your comment !

In my understanding, capturing application state within `.env` files originated from the [twelve-factor app methodology](https://en.wikipedia.org/wiki/Twelve-Factor_App_methodology) which concerns software-as-a-service applications.

However, there are many other kinds of applications, whose configuration management doesn't involve `.env` files, and even shouldn't adhere to the 12-factor methodology.

Since Just is -- unless I'm misunderstood -- a *general*-purpose project management tool, rather than a tool dedicated to SAAS projects, I think that, as a consequence, it shouldn't enforce using a `.env` file, but rather allow to use them when it makes sense, while allowing other configuration scenarios.

My proposal was an attempt to find a simple compromise that solves both #460 and this very issue, doesn't require big changes in the current codebase, and hopefully can be implemented soon, because these are one of the few limitations that prevent me from fully using & recommending Just at my work and I'd be glad to see some improvements !

Finally: would it be a big deal to type `just --envfile` instead of `just` for those who use a `.env` file ?

**Comment by runeimp** [comment]
@ngirard I don't think `just --envfile` is any bigger a deal than `just --no-dotenv`, etc. And if @casey decides to go with that, I have no problem with it at all really.

1. Neither solution is great for me as I prefer not to have to use command line options at all with my task runner. I use a task runner for efficiency and also so I don't have to remember options.  I can ultimately use hidden subrecipes to achieve my goals.
2. I very much like the idea of `just` being the central support for overriding my system environment variables via a `.env` file for a project. If the `.env` file exists then it's probably there because it's already needed for another tool in the project. It would be rare (for me) to create a `.env` only to config `just`. Though it could happen and probably already has. I just can't think of an example at the moment.
3. I believe that my idea of `JUST_DOTENV=ignore` environment variable would easily handle your use case and would only require one change to your system to resolve it. Which is exactly what environment variables are for. Though @casey's concern over it having unintended consequences could easily be applied to how `just` currently works by loading `.env` files automatically as well. Anything automatic, that has no obvious indicators that it's doing something behind-the-scenes, is likely to have unintended consequences.
4. Ultimately much of this is a judgement call. I don't think any way is particularly better than the other, beyond one way is more automatic for me (reasonable defaults for my use case and hopefully others, and is also the current default) and the other is more typing for me (intentional is always clearer/safer but also way more typing). Both options can potentially be used or switched off by `set load-dotenv := false` or `set load-dotenv := true` if that's implemented. Or if a per-recipe solution is implemented. I've never been a huge fan of _magic_ in the context of coding. I did Ruby on Rail development for almost 2 years at one point. It took me that entire time to figure out what bits of code where Ruby and what bits were RoR. I'm now primarily a Go developer (and was a PHP dev before RoR) and will take config over guess what the developer of the framework intended to be a reasonable default any day of the week. But when it comes to simple tools (tools with a simple configuration map anyway) then I'm _much_ more forgiving on this. It's not difficult to lookup what the defaults are for `just` and most of them make sense to me. I'm also a "good and efficient programmer" (AKA lazy). So I try to keep things simple when possible. Less to remember is less to forget.

I don't consider requiring `--envfile` a fix for #460:

1.  For tools like `just` I prefer YAML (JSON) or TOML over `.env` files for config.
2. I think a config file in a project folder should be loaded automatically if present for almost any tool in almost any situation. There are exception but they are rare and usually obvious. So having to specify it via command line option to load a tools standard config file is counter intuitive. At least for me. Using a CL option to load _additional_ config files makes total sense though.

BTW, I'm a little low on sleep. I apologize if any of this is coming off snide or snippy. It's not my intention at all. I love a good discussion.  👼

**Comment by runeimp** [comment]
Hey @casey, Any traction on this that I've missed? I was getting back to Templar reviewing testing I'd setup and double checked `just v0.5.10` for the support of `--no-dotenv` on the command line or `set load-dotenv := false` in the `Justfile` with now joy. So little joy...

_Just_ kidding! Joy is still to be had. Any thoughts on the `.env` ignoring situation since my last post? 🤔

**Comment by casey** [comment]
Yo! Sadly no traction. I haven't been actively adding features to Just, since another project has been consuming all my cycles.

I think `--no-dotenv` would be very easy to add, and I'd be super happy to review a PR for it, if anyone is up to the task.

**Comment by runeimp** [comment]
No prob. Mostly checking if I'd missed something. If I had any time to devote to learning Rust I'd be all over it.  😉

**Comment by casey** [comment]
@runeimp Adding `-no-dotenv` was really easy, so I went ahead and added it, and pushed `v0.5.11` with the feature. Let me know if it winds up working for your use case!

I'm going to leave this issue open, in case there's a use case that requires a statement, like `set load-dotenv := true`.

**Comment by runeimp** [comment]
Nice! I have to `echo` a reminder to remember to use it but that works for now. An option that doesn't require a reminder that affects only specific recipes would be ideal. But at least I can now continue testing and such with `just`!  😃

**Comment by casey** [comment]
I added some additional comments to the first comment in this thread. Definitely interested in feedback!

**Comment by runeimp** [comment]
@casey Love it! Still would love to have per recipe option but the three settings and their interaction with each other sounds awesome.  😃

**Comment by casey** [comment]
I just released `just` v0.8.7, which understands a new `dotenv-load` setting. `dotenv-load` currently defaults to `true`, but when `false` will disable `.env` file loading entirely:

```
set dotenv-load := false

foo:
  # no .env file will be loaded
```

I'm uncertain whether or not to change the default to `false`. I think it's better not to load `.env` files by default, but I think it's a very minor win, and might not be worth the disruption.

The steps to change the default would be:

1. Warn if a `.env` file is loaded, but `dotenv-load` is not set to `true`
2. Change the default to `false`

My main concern is that step 1 would lead to warnings for people who happened to have a `.env` file where `just` would find it, and aren't bothered by the fact that `just` loads that file, even if it isn't actually useful.

**Comment by runeimp** [comment]
@casey I'd recommend these steps:

1.  if a `.env` file is found but `dotenv-load` is not set at all then give a warning about the secret auto loading of the `.env` file and that `dotenv-load` defaults to `true` but will default to `false` in a future version. People will see the warning and either care about if the file is loaded automatically or not (or just to get rid of the warning) and set `dotenv-load` to either `true` or `false`. Otherwise they ignore the warning.
2. Eventually switch the `dotenv-load` default to `false` and continue issuing the warning with the update that the default is now `false` when a `.env` file is detected but `dotenv-load` is not set.
3. Maybe In `just v2` or some such, you remove the warning all together.

**Comment by ngirard** [comment]
I agree with @runeimp's plan. For sure I'd vote for switching `dotenv-load` to false by default.

Cheers !

**Comment by casey** [comment]
@runeimp Good idea about continuing to issue a warning after the default changes. I was planning on removing the warning and changing the default at the same time, but that would have meant that the warning went away at the exact time that breakages were likely to occur, which is when warnings would actually do the most good.

@ngirard Thanks for chiming in!

I think I'm going to go for it. I added an explanation of the change, as well as a timeline that should give people plenty of time to avoid breakages.

**Comment by dionjwa** [comment]
I am really pro loading `.env` files by default, it's consistent with other tooling, and is what you want most of the time. When you don't want it, then you should be specifying that manually. Also, I have a LOT of justfiles to manually update across many repositories. 

CI environments don't have a `.env` file typically so you have a natural separation between local and CI systems. You're in charge, it's a great tool, but I disagree with this binary decision.

In any case THANK YOU for your work on this, and giving the decision a lot of thought.

**Comment by casey** [comment]
Thanks so much for commenting, and sorry for the disruption.

> Also, I have a LOT of justfiles to manually update across many repositories.

Again, sorry for the disruption. It might not help much, but you can suppress the warning for now if you set the environment variable `JUST_SUPPRESS_DOTENV_LOAD_WARNING` to `1`, although you'll still have to update the justfiles eventually.

> CI environments don't have a `.env` file typically so you have a natural separation between local and CI systems. You're in charge, it's a great tool, but I disagree with this binary decision.

I appreciate the feedback, I definitely know it's not ideal for all use-cases.

**Comment by jonathanstrong** [comment]
> Again, sorry for the disruption. It might not help much, but you can suppress the warning for now if you set the environment variable JUST_SUPPRESS_DOTENV_LOAD_WARNING to 1, although you'll still have to update the justfiles eventually.

I'm in the same boat as @dionjwa, very much liked the existing setting (also huge fan and user of just!). 

I came to this thread looking for a way to tell just to always load `.env` files - is there one? For now `JUST_SUPPRESS_DOTENV_LOAD_WARNING` will make the warning go away, but is there a `JUST_DOTENV_LOAD=1` env var I can put in my `.bashrc` and go back to being a happy, productive just user?

**Comment by casey** [comment]
> I'm in the same boat as @dionjwa, very much liked the existing setting (also huge fan and user of just!).

Thanks for the feedback! I decided to make the change based on feedback, and the thought that `.env` loading automatically might be surprising, since having a `.env` file is super common, and having `just` unexpectedly load it could be unwelcome. It's really hard to gauge on GitHub whether a change is a net positive or negative. I wish there was a more systematic way of doing it, rather than just opening an issue and gauging from comments.

> I came to this thread looking for a way to tell just to always load `.env` files - is there one? For now `JUST_SUPPRESS_DOTENV_LOAD_WARNING` will make the warning go away, but is there a `JUST_DOTENV_LOAD=1` env var I can put in my `.bashrc` and go back to being a happy, productive just user?

That would obviously be super convenient, but it's the kind of feature that I couldn't add, since a `justfile` should work the same way regardless of external configuration. So global configuration options should only cosmetic, e.g. like `JUST_SUPPRESS_DOTENV_LOAD_WARNING`.

**Comment by jonathanstrong** [comment]
> global configuration options should only cosmetic

perhaps a command line flag, then?

as it stands currently, the warning is still emitted for `$ just --dotenv-path .env recipe-name`, suggesting that `--dotenv-path` is not enough to prompt loading of .env files without the setting in the justfile. however, there are several options in the help menu that seem to be cases where how just is invoked would change how a justfile works, e.g. `--shell` which changes which shell is used.

thanks for your consideration!

**Comment by casey** [comment]
> as it stands currently, the warning is still emitted for `$ just --dotenv-path .env recipe-name`, suggesting that `--dotenv-path` is not enough to prompt loading of .env files without the setting in the justfile. however, there are several options in the help menu that seem to be cases where how just is invoked would change how a justfile works, e.g. `--shell` which changes which shell is used.

I would definitely accept a PR for a `--dotenv-load` flag which force the `dotenv-load` setting to true, that seems pretty reasonable.

**Comment by dionjwa** [comment]
The UX of `--dotenv-load` is not ideal though:

 -  anywhere where you have aliases or similar, you are going to have to add that command flag. 
 - anywhere where you have aliases, you're a human using this, not a CI machine, and in those cases you 99% want that `.env` consumed. 
 - starting with just typing `just` to get the menu means now you have to remember to type this extra command to get expected behaviour. The point of the `.env` file is to preserve custom settings, having to then use a CLI flag breaks the great UX of `just`, where four letters opens the menu.

 To me this difficulty of deciding where to put the flag/feature/setting points to the wrong default.

**Comment by casey** [comment]
> The UX of `--dotenv-load` is not ideal though:

That's all true.

> To me this difficulty of deciding where to put the flag/feature/setting points to the wrong default.

But `--dotenv-load` is just kind of a hack to avoid having to update justfiles. The non-hacky approach is to put `set dotenv-load` in justfiles, which doesn't have any of these downsides.

**Comment by casey** [comment]
It is done! Will be in a new release shortly.
