### ISSUE TITLE
(Question) Calling one task from another

### ISSUE THREAD

**Issue by mare-imbrium** [casey/just#619]
I'd like to call a task from another task. Is this supported ?

Usually, this would happen based on some logic within an embedded bash script. It would be conditional, so it is not a dependency.

Thanks a lot.

**Comment by casey** [comment]
Hi there!

Unfortunately, this is not currently supported. One workaround is to re-invoke `just` from within the recipe:

```
bar:
  echo bar

foo:
  # do stuff
 just bar
  # do stuff
```

This is definitely an unfortunate limitation, and a commonly requested feature. I haven't been able to think of a good way to implement it, however, since just doesn't parse at all recipe bodies. It just extracts them as lines of text and passes them to the shell.

This has the nice effect that just is completely agnostic to the syntax of the shell. The downside, however, is that there isn't to add `just` functionality in the middle of a recipe.
