### ISSUE TITLE
Dynamic/conditional variables definition and substitution

### ISSUE THREAD

**Issue by mortoray** [casey/just#674]
Is there any way to do conditional variable substitution or setting?

For example, I have a task where I need to map release modes, and I'd like to do something like this:

```
build mode="release":
  npx --mode={{mode == release ? production : development}} ...

  copts := {{mode == release ? "-O3" : "-ggdb" }} ...
  clang {{copts}} A...
  clang {{copts}} B...
```

I'm not sure how to best accomplish this.

**Comment by casey** [comment]
There are sort of two pieces to this, one is a ternary operator, as in `{{mode == release ? production : development}}`, and the other is being able to assign to Just variables in the middle of a recipe, as in `copts := {{mode == release ? "-O3" : "-ggdb" }}.

I think a ternary operator would be a good addition, although one impediment is that Just doesn't have boolean values, and in fact, the only type is string. So, adding a second type would mean that Just would have to become statically typed or dynamically typed. I have a very strong preference for static typing, so I wouldn't want to make it dynamically typed, but a static type system is a lot of work. (Or, maybe I'm just assuming, I've never written one.)

As for being able to assign to a Just variable in the middle of a recipe, Just doesn't do any parsing of the body of a recipe, since it doesn't know anything about which language is being used.

One thing you could do is turn your recipe into a shebang recipe, which isn't executed line-by-line, which would let you do normal shell variable assignment:

```
foo bar:
  #!/usr/bin/env bash
  set -euxo pipefail
  a={{bar}}
  echo $a
```

**Comment by mortoray** [comment]
I do the bash approach now, but it really isn't pleasant:

```
	webpack_mode=$([[ {{mode}} == release ]] && echo production || echo development)
```

I don't know much about the internals, but my estimation (having written several languages/DSLs/VMs) is that some kind of limited typing is likely less work than you expect. :)

As to the variables, couldn't "just" understand the body of targets that aren't using a different interpreter? I don't mind using bash, though I find I'm using it for a lot of small scripts only because some small features are missing.

**Comment by casey** [comment]
Yeah, that's pretty bad T_T

So far I've studiously avoided trying to interpret the bodies of recipes. There are a lot of different `sh`s out there, and the bourne shell language is so free form that there would be weird edge cases, like if the user does `echo := foo`.

**Comment by kenden** [comment]
I have another example where conditional logic would help.  

Here, I would like to define `TAG_HASH` at the beginning of the justfile.  
This variable is reused in many targets so I don't want to re-set it in each target: it should be set once.
```make
# if running in jenkins, set the tag to the git sha of the folder, else, create a hash of the folder
FOLDER_HASH := `find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
FOLDER_GIT_SHA := `git log -1 --oneline docker/myfolder | cut -d' ' -f 1`
TAG_HASH := `[[ "{{JENKINS_URL}}" != "" ]] && echo {{FOLDER_GIT_SHA}} || echo {{FOLDER_HASH}}`
```
That last line is already not very readable, but `{{JENKINS_URL}}`, `{{FOLDER_GIT_SHA}}` and `{{FOLDER_HASH}}` are empty in the line above.
(because the variables inside `{{ }}` are not replaced by their values (this happens only at the beginning of the file, it works in targets. Could it be  a bug?).

I got it working with:
```make
TAG_HASH := `[[ -n "${JENKINS_URL}" ]] && git log -1 --oneline docker/myfolder | cut -d' ' -f 1 || echo -n dev-;find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
```
But this is nasty.
So having a way to use 'if/else' in just, or implement some kind of equivalent for `ifeq` (see https://github.com/casey/just/issues/262) would help a lot. For example:

```make
JENKINS_URL := env_var_or_default('JENKINS_URL', "")
if (JENKINS_URL != "" ) {
  TAG_HASH := `git log -1 --oneline docker/myfolder | cut -d' ' -f 1`
else {
  TAG_HASH := `find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
}
```

**Comment by casey** [comment]
So far, the code outside of recipes isn't imperative, in the sense that it doesn't run line-by-line, and everything is evaluated at the same time and dependencies between items is resolved automatically. This is why you can write variable assignments out-of-order, like this:

```
bar := foo
foo := "hello"
```

I'd like to preserve that, and allowing conditionals at the top level like this might complicate that. But, I think adding a ternary expression, `if-empty CONDITION { IF } else { ELSE }`, is totally reasonable. I opened #696 to track that. A ternary operator doesn't fully address the original issue here, conditionals inside of recipes, so I'm going to leave this issue open.

**Comment by casey** [comment]
It is done! See [my comment in #696](https://github.com/casey/just/issues/696#issuecomment-716923105) for more details. Thanks to all for requesting and discussing this feature.

**Comment by casey** [comment]
I only added conditionals expression, not `#ifdef`-like conditional evaluation, so if there are use cases that are hard to do with conditionals feel free to create a new issue.

**Comment by kenden** [comment]
I could get my example above 
~~~
TAG_HASH := `[[ -n "${JENKINS_URL}" ]] && git log -1 --oneline docker/myfolder | cut -d' ' -f 1 || echo -n dev-;find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
~~~

Simplified as:
~~~make
JENKINS_URL := env_var_or_default('JENKINS_URL', "")
FOLDER_HASH := `find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`  # hash the folder 
TAG_HASH := if (JENKINS_URL != "" ) { `git log -1 --oneline docker/myfolder | cut -d' ' -f 1` } else { FOLDER_HASH }
~~~

Much better!
It could still benefit from some ifdef-like feature to be more readable I think.

**Comment by casey** [comment]
@kenden Nice!

The thing that makes ifdef challenging is that the both branches of the ifdef would have to set the same variables.

For example:

```make
if foo == bar { x := "a" } else { y := "z" }
````

One branch sets `x` and the other sets `y`, which makes knowing which variables are in scope impossible.

I'd like to be able to support this, which I think would also be more readable:

```make
JENKINS_URL := env_var_or_default('JENKINS_URL', "")
TAG_HASH := if JENKINS_URL != ""  {
   `git log -1 --oneline docker/myfolder | cut -d' ' -f 1`
} else {
  `find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
}
```

Currently, this is not allowed because constructs aren't allowed to span multiple lines. I opened #713 to track allowing multi-line expressions. I hope to do this by keeping track of whether there is an open delimiter in the lexer (`[{(`), and if there is, not emitting an Eol token. This would make the above code work without needing to add explicit line continuations. (Like `\` at the end of the line.)

**Comment by casey** [comment]
Oh, btw, you don't need `(..)` around conditions.

**Comment by casey** [comment]
@kendon I just released [v0.8.3](https://github.com/casey/just/releases/tag/v0.8.3) with PR #717, which ignores newlines when there are unclosed delimiters. This includes `{`, `(`, and `[`, so the above example I wrote should work.

I think this is a nice improvement, both for long `if` expressions, but also just in general, since `(` can now be used to split any kind of expression into multiple lines, like Python.

**Comment by kenden** [comment]
Hi @casey, nice, thank you!
this is how the example looks now:
```make
JENKINS_URL := env_var_or_default('JENKINS_URL', "")
# get the git sha of the folder if running in jenkins, else the md5 of the folder 
TAG_HASH := if JENKINS_URL != "" {
              `git log -1 --oneline docker/myfolder | cut -d' ' -f 1`
            } else {
              `find docker/myfolder -type f | sort -u | xargs cat | md5sum | cut -c1-7`
            }
```

**Comment by casey** [comment]
@kenden Sweet, much better!
