### ISSUE TITLE
Create windows installation package

### ISSUE THREAD

**Issue by vmiheer** [casey/just#710]
`Winget` doesn't seem to support direct copy-paste (download) of binary. Instead it seems to need some sort of package in format:
[inno, wix, msi, nullsoft, zip, appx, msix and exe](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md).

**Comment by vmiheer** [comment]
Or we can wait for https://github.com/microsoft/winget-cli/issues/140

**Comment by casey** [comment]
Thanks for creating this issue! I think it's useful to track creating a windows installer. Do you happen to know which type of installer is easiest to create?

Ideally one that can be used on GitHub Actions to create an installer from a text manifest that can be committed to the repo.

**Comment by vmiheer** [comment]
I have never worked with creating installer. :)

**Comment by casey** [comment]
Fair enough! I think wix is maybe the best option, but I don't know for sure.

**Comment by michidk** [comment]
I have used Wix before, and it was not a really great experience to work with.
Sadly winget still doesn't support .zip files nor .ps1 scripts, but it seems like these features are in the pipeline.

The easiest way to implement a winget package right now would be to just upload the .exe to the GitHub releases since this is supported. 

The other problem is that it seems difficult to maintain a winget package: You can't use a URL to the latest release, since you have to provide a hash of the file in the manifest. So you have to update the package for every new just version. But publishing a new version requires a PR in the winget-pkgs repo. For the chocolatey package I use GitHub actions to automatically publish new versions - we would need something similar as well to create the packages and PRs. Maybe there is already a solution for that?

So maybe we just wait until those problems are solved.

**Comment by kenden** [comment]
[microsoft/winget-cli#140](https://github.com/microsoft/winget-cli/issues/140) is now implemented, so it's possible to simply use a .zip file now.

**Comment by casey** [comment]
> [microsoft/winget-cli#140](https://github.com/microsoft/winget-cli/issues/140) is now implemented, so it's possible to simply use a .zip file now.

Dope! If anyone knows what the command would be, let me know so I can include it in the readme.

**Comment by JakeOShannessy** [comment]
It looks like a manifest (which reference this zip file from this repo) has been added to the winget package repository. Therefore just can now be installed with:

```
winget install Casey.Just -e
```
