### ISSUE TITLE
Use variables created in command

### ISSUE THREAD

**Issue by GiteZz** [casey/just#724]
Hey,

I'm trying to accomplish something like this:

```
setup-placeholder:
    id := `curl ####.com`
    curl -d "result={{ id }}}" ....
```

But just complains that variable id is not defined. I tried with id = $(curl ####.com) and then use $id, but that did not work either.

Thanks in advance!

**Comment by casey** [comment]
Hi there!

Inside of a recipe, all lines are executed by the shell, not just, so it's not possible to set just variables. (With `:=`.) Also, every line is executed by a new shell instance, so if you set a shell variable (with `x=y`) it won't be set in the next line.

This can be overcome by turning the recipe into shebang recipe. In a shebang recipe, the whole recipe is extracted and run as a script, so the whole thing is run by one shell instance, so setting variables works.

Here's how that would look:

```
setup-placeholder:
  #!/usr/bin/env bash
  id=`curl ####.com`
  curl -d "result=$id" ....
```

**Comment by casey** [comment]
This is a really common question, so I added a new [section of the readme](https://github.com/casey/just#setting-variables-in-a-recipe), which hopefully does a good job of explaining what's happening and what the workarounds are.

I also added [a section](https://github.com/casey/just#safer-bash-shebang-recipes) about using `set -euxo pipefail` in bash shebang recipes. This isn't specific to Just, and is a good idea in any Bash script, but I added it because it makes Bash shebang recipes behave more like normal recipes in some useful ways.
