### ISSUE TITLE
Allow customization of the help first line: "Available recipes:"

### ISSUE THREAD

**Issue by dionjwa** [casey/just#738]
Use case: 

I have "generic" justfiles, and then "specific" justfiles:
```
./justfile
./extra.justfile
```
`./justfile`: generic
`./extra.justfile`: "specific"

The `extra.justfile` is actually called via the `justfile`:

```
# Extra service specific commands
@extra args="":
    if [ -f extra.justfile ]; then \
        just --justfile extra.justfile {{args}}; \
    else \
        echo "none"; \
    fi
```

where the `extra.justfile` might look like:

```
_help:
    #!/usr/bin/env bash
    set -euo pipefail
    echo -e "  Extra tools:"
    echo -e ""
    just --list --unsorted --justfile extra.justfile
    echo -e ""

test_extra:
    echo foo
```

I want the help from the first to be something like:

```
Available recipes:
    init                 # blah1
    apply             # blah2

   extra commands:

   test_extra      # blah3
```

Notice there's no "Available recipes:" line in the second. Otherwise there's two "Available recipes:" which is confusing and not aesthetic.

Ability to customize the indentation of the printed recipes would also be useful for this use case. Basically this is a workaround for not being able to nicely compose separate justfiles.

Thank you! This tool is great, and I use it every day. And thanks for being so responsive to requests and bugs.

**Comment by casey** [comment]
> Thank you! This tool is great, and I use it every day. And thanks for being so responsive to requests and bugs.

You are most welcome! I love the fact that other people find it useful, and that it's made its way into people's everyday habits and programming projects :3

I think the formatting got messed up in your example. Is this what you're thinking of?

```
Available recipes:
    init  # blah1
    apply # blah2
    extra # blah3

Extra commands:
    foo # blah4
    bar # blah5
```

Or were you thinking of having different indentation for the items in the list?

I think this would be super easy to do.

We could add a `--list-heading` option that takes an argument. The argument will be printed instead of `Available recipes:`. So you you would do:

  ```
  just --justfile extra.just --list --list-heading 'Extra commands:'
  ```

For modifying indentation, we could add a `--list-indentation` option that takes an argument, which is printed before every list entry, and replaces the default four spaces.
 
  ```
  just --justfile extra.just --list --list-indentation '      '
  ```

Ideally you should be able to suppress the heading entirely, so you could also do:

```
Available recipes:
    init  # blah1
    apply # blah2
    extra # blah3
    - foo # blah4
    - bar # blah5
```

Passing spaces and a dash  to `--list-indentation` for the second justfile. Or maybe spaces and `extra`, to get:

```
Available recipes:
    init  # blah1
    apply # blah2
    extra # blah3
    extra foo # blah4
    extra bar # blah5
```

(I don't think it's currently possible to get a recipe to not print in `--list` without adding an underscore to the front of the name, so `extra` would still appear on its own.)

Does that sound like it would work for your use case?

**Comment by dionjwa** [comment]
Those options would actually be super awesome, being able to customize the headings and indentation would allow me to get the help "just" how I want it :-)

**Comment by casey** [comment]
Excellent just pun.

I "just" merged #753, and released v0.8.4 which includes it. The options are `--list-heading`, to control the heading text, and `--list-prefix`, to control the indent. Note that you should also provide a newline to `--list-heading`, i.e. `Heading:\n`. This so that if you do `--list-heading ''`, it will suppress the heading entirely.

**Comment by casey** [comment]
Let me know if these work for your use case!

**Comment by dionjwa** [comment]
If I do 
```just --list --list-heading 'Commands:\n'```
I get: 
```
Commands:\n    apply *args="-- ...<rest of recipes>
```
but this works:
```
just --list --list-heading $'Commands:\n'
```
I think having to add a newline in `--list-heading` is bit counterintuitive, and not obvious in bash (I had to google it). 

Otherwise it works great! Thank you so much

**Comment by casey** [comment]
> but this works:
> 
> ```
> just --list --list-heading $'Commands:\n'
> ```

Hmm, that's annoying. I assumed that just `--list-heading "Commands:\n"`  would work, but didn't actually try it myself 😅

> I think having to add a newline in `--list-heading` is bit counterintuitive, and not obvious in bash (I had to google it).

My intention in requiring the user to supply the newline was so that `--list-heading ''` would suppress the heading line entirely. (Since the empty string would replace the heading text and the newline.)

It's definitely annoying that you have to use obscure syntax to get a newline in an argument. I'm a little hesitant to change it though, just because I'd have to add an additional flag to suppress the newline. I.e. `just --list --list-no-heading-newline --list-heading ''`.

> Otherwise it works great! Thank you so much

You're most welcome!
