### ISSUE TITLE
Create a prior art and alternatives section in readme

### ISSUE THREAD

**Issue by casey** [casey/just#745]
- Make
 - https://github.com/jakedeichert/mask
 - MS Just
 - https://github.com/egoist/maid
 - https://github.com/sagiegurari/cargo-make
 - https://github.com/VladimirMarkelov/haku
 - https://github.com/go-task/task

**Comment by casey** [comment]
I started the section and added a couple, but should still add the rest eventually: https://github.com/casey/just/pull/1008

**Comment by xonixx** [comment]
Hey @casey! You might want also to mention my creature https://github.com/xonixx/makesure

Some exclusive features of it:

1. The syntax of `Makesurefile` is a valid shell, so user [gets highlighting for free](https://github.com/xonixx/makesure/blob/main/Makesurefile).
2. The tool [doesn't need traditional installation](https://github.com/xonixx/makesure#installation), since it's single-file POSIX shell script (in fact 99% AWK) that you put in project repo. 
3. The recipe may include very simple but very powerful [`@reached_if` modifier](https://github.com/xonixx/makesure#reached_if). It allows to skip execution (together with sub-dependencies) if already satisfied (idempotence).  I wonder if `just` needs this feature and/or could incorporate.

Other than that, conceptually and feature-wise it's close to `just` except for syntax and [this](https://github.com/xonixx/makesure#omitted-features).

**Comment by casey** [comment]
Nice, that looks really cool. I especially like that it's just shell and zero install. Adding it [here](https://github.com/casey/just/pull/1299).

**Comment by xonixx** [comment]
Thank you!
