### ISSUE TITLE
Pass a value set in one recipe to another

### ISSUE THREAD

**Issue by bigjazzsound** [casey/just#750]
My team is using Justfiles for our Terraform builds. We want to have one recipe that manipulates some strings and then pass them to dependent recipes.

Here is a simplified example of what we are trying to achieve:

```
foo *args="":
	FOO="{{args}}"

bar: foo
	echo $FOO
```

foo takes in args and sets them to a variable. I then want to use that variable in bar. 

Is this possible with Just?

**Comment by casey** [comment]
There are a few ways to do this, depending on your needs.

Args can be passed to dependencies like this:

```
foo ARG: (bar ARG)

bar ARG:
	echo {{ARG}}
```

However, you can't manipulate them, aside from what's possible with expressions:

```
foo ARG: (bar ARG + "hello")

bar ARG:
	echo {{ARG}}
```

If you want to modify an argument with shell code and pass the result, then you might be stuck calling just recursively:

```
foo *args="":
  #!/usr/bin/env bash
  FOO={{args}}
  # modify $FOO
  just bar $FOO

bar FOO:
	echo {{FOO}}
```

I think this is usually okay, but, for example, you'll re-run dependencies, since the recursive invocation won't know what dependencies have already run.

Do either of these options look good

**Comment by bigjazzsound** [comment]
3 is what I am looking for because we do have to modify the arguments before passing it to the dependent recipe, but the recursion is a problem.

The amount of code we have to repeat between the two recipes is not that much, so if this is not possible it is not that big of a deal.

**Comment by casey** [comment]
Ah, that's unfortunate. In some future world, I can imagine letting recipes be called like functions and have captured output that allows manipulating argument values, but that's a long way off. Another possibility is backtick interpolation, which would let you do some simple modifications with shell:

```
foo ARG: (bar f`echo {{ARG}}foo`)

bar ARG:
	echo {{ARG}}
```

Out of curiosity, what kind of modifications do you need to do to the arguments?

**Comment by casey** [comment]
I'm going to close this, since although it's not really solved, the solution is probably a ways off.

**Comment by bigjazzsound** [comment]
> Out of curiosity, what kind of modifications do you need to do to the arguments?

I'm taking the arguments and turning them into "-target=$2 -target=$3", etc.
