### ISSUE TITLE
Can't use Just variable inside if statement

### ISSUE THREAD

**Issue by DeflatedPickle** [casey/just#758]
First of all, I'm just in love with just! Thank you so much for dedicating so much time and effort towards this project and the documentation for it

I've found a possible quirk, given my understanding of conditionals and mid-string-variables is correct
Consider the following;
```make
build debug='all':
	#!/usr/bin/env bash
	set -euxo pipefail
	debug={{ if debug != '' { "--debug {{ debug }}" } else { "" } }}
```
If I'm getting the syntax right, this should resolve to `debug="--debug all"`, however the string inside of the `if` statement isn't processed and we get the following trace:
```css
+ debug=--debug
+ '{{' debug '}}'
/tmp/justZ7hT4U/build: line 91: {{: command not found
error: Recipe `build` failed with exit code 127
```
The following does work, since the work is done by `bash`;
```bash
if [ {{ debug }} != "" ]; then debug="--debug {{ debug }}"; else debug=""; fi
```

But this isn't what I thought of first as my use-case was to have this check as an argument to a script and I wanted to cut corners. But I might just be getting my syntax wrong, wouldn't be the first time

**Comment by casey** [comment]
> First of all, I'm just in love with just! Thank you so much for dedicating so much time and effort towards this project and the documentation for it

Awesome, I'm glad you like it!

Ah, so variable interpolation is only currently supported in recipe bodies, and not inside strings. I'd like to support this eventually with a python f-string like syntax, e.g.:

```
build debug='all':
	#!/usr/bin/env bash
	set -euxo pipefail
	debug={{ if debug != '' { f"--debug {{ debug }}" } else { "" } }}
```

This is tracked in #11, so I'll close this in favor of that issue. You can tell it's a longstanding request, since it's issue number 11 😅.

I've put it off for so long because it's pretty tricky. I think it requires that the lexer get some kind of state stack, so it can track when it's inside of nested interpolations.
