### ISSUE TITLE
Setting the shell to bash/zsh prevents `--choose` from working

### ISSUE THREAD

**Issue by ngirard** [casey/just#783]
Using latest precompiled binary on Ubuntu 20.04.
Various precompiled binaries of fzf were tested with the same result, from v0.24.0 to v0.26.0.

```sh
cat <<EOF > justfile
set shell := ["bash"]
a:
  echo a
b:
  echo b
EOF
LANG=C just --choose
```
results in
```
/usr/local/bin/fzf: /usr/local/bin/fzf: cannot execute binary file
Chooser `fzf` returned error: exit code: 126
```
Commenting the first line allows `just --choose` to work.
Switching from bash to zsh makes no difference.

**Comment by casey** [comment]
Ah, sorry you ran into this. The issue is that just passes the command to be run to the shell as an argument, and most shells require an additional flag, usually `-c`, to make them evaluate the first argument.

This should work:

```make
set shell := ["bash", "-uc"]
a:
  echo a
b:
  echo b
```

(I added `-u` to make the shell exit when evaluating an undefined variable, which is usually what you want.)

This isn't very well documented, so I just added an explanation and examples to the readme: https://github.com/casey/just/#shell

If this doesn't work, please feel free to comment and reopen!
