### ISSUE TITLE
How can I switch to multiple databases using multiple .env files depends on context?

### ISSUE THREAD

**Issue by divya-sk** [casey/just#815]
I am using a single .env file to run against a single database.
Now I want to run against multiple databases using  multiple .env files depends on the different context that we are passing
For example
     if I passing the context ABC then I want to run the .abc.env file 
     ```
  just context=abc .abc.env 
    ```

**Comment by casey** [comment]
I don't think this is currently possible. There are a few open issues covering things like [choosing the dotenv file with a flag](https://github.com/casey/just/issues/802), and another for [dotenv-related settings](https://github.com/casey/just/issues/469). Do either of those look like they would work for your use-case?

**Comment by casey** [comment]
#941 added flags to control `.env` file loading, which helps with this, so I'm going to go ahead and close it. It isn't possible to set the `.env` file based on another variable, but I can't think of a good way to do that, because `.env` file loading has to happen before variable evaluation, since variable evaluation can depend on the variables from the `.env` file.
