### ISSUE TITLE
Re-run chooser tests if they fail

### ISSUE THREAD

**Issue by casey** [casey/just#849]
Sometimes the chooser tests fail spuriously. We should re-run them a few times until they pass.

**Comment by 06kellyjac** [comment]
Is this a chooser test? https://github.com/casey/just/blob/50cd24d37ba696dd74f3b05f1c23b934ef049b10/src/justfile.rs#L429-L450

I've had it fail randomly a couple times with "Text file busy"

**Comment by casey** [comment]
@06kellyjac That's interesting, that's not a chooser test. Is that the only test you've seen fail with that error?

**Comment by 06kellyjac** [comment]
Yeah and I couldn't get to fail consistently. It failed when building the latest update using nix with this patching (the original sed on the left): https://github.com/NixOS/nixpkgs/pull/125653/files#diff-85969503e7886ff0bcdf36e5c35be3b9fa6cd334be07e99d9948a4643bcbe90eL38-L43

We patch these shebangs because `env` doesn't have access to anything in the sandbox.
I thought there might be an issue with the patching of `#!/usr/bin/env sh` to use bash, which could be used at the same time as another test that uses `bash` but I don't see why there'd be a "Text file busy" error for two processes trying to run `bash` :shrug:

I don't have the output of the issue in my terminal anymore so I'll try recreate the error
I'll also move this discussion to a new issue to avoid filling this one with non-chooser test stuff

**Comment by casey** [comment]
I haven't seen an error for these in a while, so I think this is fixed somehow 🤷‍♂️
