### ISSUE TITLE
Defining shortcuts for setting multiple variables from the command line?

### ISSUE THREAD

**Issue by IndianBoy42** [casey/just#875]
I use Justfiles for installing my system and programs, one thing that is super useful is being able to set a variable at the top of the Justfile for where to install to. I can then change this from the CLI to install to a user or the whole system.

But i still have to remember and type the whole path, which is somewhat verbose.
I tried to use something like:
```
as-root name:
    just installto='/usr/local/' {{name}}
```

Essentially make a recipe that recursively calls another recipe with some variables set. One drawback is I can no longer run multiple recipes at a time. So varargs like functionality would be good. But a more general solution is to allow defining some shortcuts that set one or more variables
```
--as-root:
    installto := '/usr/local'
--as-user:
    installto := '~/.local/'
```

An even more general method may be to allow setting variables from recipes such that a recipe that is invoked after would see the new value of the variable
```
as-root: # use `just as-root install`
   installto := '/usr/local'
install:
   install to {{installto}}
another-recipe:
   as-root # variables set in this recipe seen by the future commands
   install
```

This would allow even more code reuse and cleaner code. 

Also I'm sure many people already ask for this but a way to change the working directory that affect all the lines below it or from a dependency (without necessarily going to a shebang recipe) would be great too

**Comment by casey** [comment]
I have some ideas for work arounds. One thing you could do is have a variable which is just the name of the binary, and another that's the full path, so you only have to set the name on the command line:

```
name := "default"
path := "/usr/local/" + name

install:
  cp bin {{path}}
```

You could then do:

```
just name=foo install
```

You could also forward additional arguments from `as-root`, which would allow you to run multiple recipes:

```
as-root name *args:
    just installto='/usr/local/' {{name}} {{args}}
```

So you could then do, for example:

```
just as-root foo build install
```

For changing a directory, there's no way to change a directory for a whole justfile, but you can change a recipe to a shebang recipe, which will execute the whole recipe with one shell, instead of using a shell for each line:

```
foo:
  #!/usr/bin/env bash
  set -euxo pipefail
  cd foo
  pwd
```

(`set -euxo pipefail` isn't strictly necessary, but it turns on a number of nice things, for example terminating the script if a command fails.)

Let me know if these work for your use case.

**Comment by IndianBoy42** [comment]
I actually want to change the path from the command line, not the name, for example to install for one user '~/.local/' or for all users in '/usr/local'. This also requires changing some commands to use sudo, so its not just one variable at a time
There are also some other cases where I want to replace what command is used to install (such as switching between only downloading vs dl + install).
in all of the above examples, 99% of cases its going to be one of 2-3 possibilities but the command line arguments become quite complicated. So it would be nice to have a shortcut of just 'just --dl' or 'just --install' that swaps out all the variables at once

The varargs + a subcommand that recursively calls just might work for most cases. 

The shebang recipe mostly works, but i like the interleaving of printing commands with there output that you can get from linewise recipes. and also it doesnt persist from dependency to recipe or between recipes which would be useful in some cases

**Comment by casey** [comment]
> I actually want to change the path from the command line, not the name, for example to install for one user '~/.local/' or for all users in '/usr/local'. This also requires changing some commands to use sudo, so its not just one variable at a time

What about:

```
name := "foo"
prefix := "/usr/local/bin"
path := prefix + "/" + name
sudo := if use-sudo == "1" { "sudo" } else { "" }
use-sudo = "0"

install:
  {{sudo}} cp bin {{path}}
```

> The shebang recipe mostly works, but i like the interleaving of printing commands with there output that you can get from linewise recipes.

The `x` in `set -euxo pipefail` will actually make `bash` print out lines as they're executed.

**Comment by IndianBoy42** [comment]
Hmm, yeah with enough conditionals I could probably achieve the same effect

I actually use fish shell for my terminal and for most scripting, which doesnt have equivalents of 'e' and 'x' afaict, which are the parts that I really like. I have to manually prepend each line with `and` to simulate `set -e`

**Comment by casey** [comment]
The reason that I suggest workarounds is because things like this:

```
--as-root:
    installto := '/usr/local'
```

…where something is done inside of a recipe, that isn't just a command, would represent a major change in how `just` operates. Currently, recipe lines are just text that gets passed to whatever shell is being used. `just` doesn't interpret them in any way. I have thoughts about how to do this, but it's probably a longer-term project, so I'm going to close this issue for now.
