### ISSUE TITLE
Bash Heredoc Support

### ISSUE THREAD

**Issue by mihaigalos** [casey/just#881]
Hello,

I understand each `justfile` line executed as a separate command, since (from the docs):

> Recipes without an initial shebang are evaluated and run line-by-line, which means that multi-line constructs probably won’t do what you want.

I would, however, like heredoc support, so that I can write multiline heredoc such as the following, without requiring a shebang:
```bash
generate_justfile:
    cat <<EOF > generated/Justfile
    default:
      @just --list
    EOF
```

**Comment by casey** [comment]
I don't think that's currently possible. You could do this:

```
generate_justfile:
    cat <<EOF > generated/Justfile \
    default: \
      @just --list \
    EOF
```

But I think just would mangle the indentation in that case, and the string wouldn't be correct.

Using a shebang recipe isn't perfect, but wouldn't be too bad:

```
generate_justfile:
    #!/usr/bin/env bash
    set -euxo pipefail
    cat <<EOF > generated/Justfile
    default:
      @just --list
    EOF
```

Another option would be to use a variable:

```
export DEFAULT_JUSTFILE := '''
    default:
      @just --list
'''

generate_justfile:
	printf '%s' "$DEFAULT_JUSTFILE" > generated/Justfile
```

The dance with an exported environment variable and `printf` is to prevent the shell from interpreting any special characters in the justfile.

I'm going to go ahead and close this. It would be useful to support heredocs in linewise recipes, but I can't see a clean way to do that. Do let me know though if one of the above options works for your use-case.

**Comment by filipdutescu** [comment]
Would it be possible to add this in the manual? It is exactly what I needed for my use case!

**Comment by casey** [comment]
@filipdutescu I'm not opposed, although I'm not exactly sure where in the readme it would go, or how it would be worded 🤔

**Comment by filipdutescu** [comment]
Maybe it could have it's own section? Or maybe a generic "Advanced usage"/"Tips and tricks"? Could be in a "Troubleshooting" or "Examples" section as well. Just throwing out some ideas.

For wording, for me, if you can find it relatively easily by searching for the `just heredoc` words is enough.

**Comment by casey** [comment]
I think that's reasonable. Can you elaborate a little bit on what was the thing that was helpeful? Was it that you can do dedented strings with ```'''…'''```, or was it the bit with using `printf` to print them?

**Comment by filipdutescu** [comment]
Yes, sorry, I completely forgot to do that! The combination of the two mostly, but the other alternatives also helped, since I saw different options and could better understand what worked for my use case.

I just never thought of the `printf` option at all until I saw it here!

Thanks a lot for considering this and working with me to make it happen!

**Comment by casey** [comment]
I [added a section](https://github.com/casey/just?tab=readme-ov-file#printing-complex-strings) to the readme, which tries to mention everything together about printing complex strings, like using triple-quoted strings, `printf` instead of echo, and exporting them. It also mentions heredocs. I think it's a good addition, because all this is quite esoteric.

**Comment by filipdutescu** [comment]
This is perfect! And very detailed! Thank you very much for the time and effort!
