### ISSUE TITLE
Hierarchical Override ala direnv source-up

### ISSUE THREAD

**Issue by MadBomber** [casey/just#885]
Color me "late" to the discovery of how wonderfully powerful 'just' can be as a generic project assistant.  I would love to have an ability within just similar to the source-up capability of the direnv tool in which I can define a hierarchical set of justfiles or not.

Lower-level (directory-wise) justfiles with the "set source_up" would add to and/or replace the recipes of higher-level justfiles.

Dewayne
  o-*

**Comment by casey** [comment]
Thanks for the kind words!

This is definitely something that I want to support. Currently, the plan is to add the ability to define modules, and be able to use recipes within those modules as subcommands.

So you could have, in `my-project/Justfile`:

```
mod foo
```

And then in `my-project/foo/mod.just`:

```
bar:
  echo bar
```

And then anywhere in the project you could do `just foo bar` to call the `bar` recipe in `foo/mod.just`.

This project is tracked in #383, but it's going *very* slowly. It's something that I want to support, but it's a big change, and I don't personally have the bandwidth to work on it right now.

One thing that makes it hard is that it requires changing a whole bunch of stuff. As just one example, error messages now need to point to the correct justfile. Which is why it's going so slowly.

I'm going to close this issue, since I think it's mostly captured by #383, but let me know if I'm missing something!

**Comment by MadBomber** [comment]
Sorry it took a while to come back to this.  Your module concept sounds fine. 
 
I did an experiment to see whether the hierarchical process was in fact useful.  It is. The first thing I did was to disable the DuplicateRecipe error processing by commenting out the code and test blocks in several places. In this approach there is no such thing as a duplication.  That goes for aliases and variables as well.  I did not disable those for this experiment.  Duplicates are now over-rides or maybe re-definitions.

The next thing I did was a quick and dirty wrapper via bash alias of the justfile using m4 as a preprocess.  In the justfile.m4 I used an "include(../justfile.base)" macro.  The result via STDOUT went to "justfile"  Then I used the "target/debug/just" to see what would happen.

I got access to the unique recipes from the justfile.base and those that were duplicated, the last definition was used as the over-ride as expected.

BTW After I glorified "just" in an internal post at the company, my lead told me that just is actually used by our devops/deployment group.  See what I miss when my nose is in the code.

Dewayne
  p-*

**Comment by casey** [comment]
> I did an experiment to see whether the hierarchical process was in fact useful. It is. The first thing I did was to disable the DuplicateRecipe error processing by commenting out the code and test blocks in several places. In this approach there is no such thing as a duplication. That goes for aliases and variables as well. I did not disable those for this experiment. Duplicates are now over-rides or maybe re-definitions.
> 
> The next thing I did was a quick and dirty wrapper via bash alias of the justfile using m4 as a preprocess. In the justfile.m4 I used an "include(../justfile.base)" macro. The result via STDOUT went to "justfile" Then I used the "target/debug/just" to see what would happen.
> 
> I got access to the unique recipes from the justfile.base and those that were duplicated, the last definition was used as the over-ride as expected.

That's a super interesting experiment, I would never have thought to try that.

> BTW After I glorified "just" in an internal post at the company, my lead told me that just is actually used by our devops/deployment group. See what I miss when my nose is in the code.

Awesome!
