### ISSUE TITLE
Is `Justfiles` extendable. ? 

### ISSUE THREAD

**Issue by pshanoop** [casey/just#906]
We have a Mono-Repo. Where we have 30+ services (growing), Each of these services have its own `Makefiles`, Most build scripts are repeated there so changing anything takes many boring hours.  

Now, Just come over this the `justfiles`. Is there any possibility to have extendability. 

For example, We have a `justfile` with all those common functions we need for all micro-services. This `justfile` somehow refered/included to all other micro-service's `justfiles`. 

Btw, thanks for making it. 👍🏾

**Comment by casey** [comment]
Unfortunately nothing like that is possible at the moment. Some kind of module system or import statement is a longstanding desire, but I just haven't done it yet. I really want to do it, because a lot of people have asked for it, but I can't promise any specific timeline Check out #383 for discussion of modules, and #237 for discussion of some kind of import statement.

There is a pre-processor by @MadBomber that might do what you want, although I think the error messages might suffer a bit: https://github.com/MadBomber/justprep

> Btw, thanks for making it. 👍🏾

Thank you for the kind words! It definitely keeps me motivated :3

**Comment by pshanoop** [comment]
Thanks for the reply and link, 
I will look into `justprep`. Keep the energy, You certainly helped many :)
