### ISSUE TITLE
Why do binary releases include build-related stuff?

### ISSUE THREAD

**Issue by VladimirMarkelov** [casey/just#952]
I checked archives with binaries of the `0.10` release: all of them contain files `Cargo.toml` and `Cargo.lock`. I do not think an end-user needs those files.

**Comment by casey** [comment]
`Cargo.toml` is actually pretty useful, since it gives the exact versions and hashes of dependencies that were used to produce the binary. This allows, for example, checking if a dependency has a known security vulnerability. `Cargo.toml` is less useful, but it does have some useful metadata, for example the project name, repo, and developer email addresses, so I'm inclined to leave it in unless there's a strong downside to doing so.

**Comment by VladimirMarkelov** [comment]
I see your point. Thanks for the explanations. I always look for emails and alike info in READMEs. License file usually includes email and name of its developer. But I do not mind having those files inside the archives. The only possible trouble is when another utility contains the same files: when a user unpacks into the same folder, `Cargo.*` files would confuse the user as it is unclear which file they belong to.

**Comment by casey** [comment]
That's true, the filenames don't do much to tell you what they're for. Although clashes are probably inevitable, if users unpack the archive without creating a subdirectory.

**Comment by runeimp** [comment]
People tend to create their own pain. Unarchiving a file into a directory full of files without knowing if it will create its own subdirectory either because it's embedded in the file or via command option is a great example of such.

"Mic drop", owe! Why are my arms so short!
