### ISSUE TITLE
invocation_directory incorrect on Windows (nushell) 

### ISSUE THREAD

**Issue by hustcer** [casey/just#984]
With the following `Justfile`:
```just
set shell := ['nu', '-c']

JUST_INVOKE_DIR := invocation_directory()
```

Use `just --evaluate` to show env vars will got:
```
JUST_INVOKE_DIR := "/d/Data/iWork/termix-nu"
```
However the path is invalid:
```nu
> ls /d/Data/iWork/termix-nu
error: No matches found
  ┌─ shell:5:4
  │
5 │ ls /d/Data/iWork/termix-nu
  │    ^^^^^^^^^^^^^^^^^^^^^^^ no matches found
```

Env:
---
just version: 0.10.2

nushell version detail:

|key|value|
|-|-|
|version|0.37.0|
|short_commit|f9ae8820|
|commit_hash|f9ae882012e87e328adbe8da90d3a37ba8aa0448|
|commit_date|2021-09-14 19:45:30 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.55.0 (c8dfcfe04 2021-09-06)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.55.0 (32da73ab1 2021-08-23)|
|pkg_version|0.37.0|
|build_time|2021-09-14 20:08:37 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by casey** [comment]
This is a consequence of a somewhat weird compatibility hack. I originally thought that the most common way to run just on windows would be with a unix userland provided by cygwin. Cygwin userland tools (`cp`, `rm`, etc) expect forward-slash-separated paths, like `/d/Data/iWork/termix-nu`, so `just` translates the invocation directory,  which is a windows-style path, into a forward-slash-separated path.

Since you're using nushell, which doesn't understand these unix-style paths, you get an error when you try to use it.

I believe this error is specific to `invocation_directory()`, since `cygpath` isn't used in a user-visible way otherwise.

Given the benefit of hindsight, maybe doing this translation isn't a good idea, since it's very confusing, but changing it now might not be a good idea for backwards-compatibility.

One option would be to add an `invocation_directory_native()` function, which would always return a native path, without doing the translation with `cygpath`.

**Comment by hustcer** [comment]
> One option would be to add an invocation_directory_native() function, which would always return a native path, without doing the translation with cygpath.

Thanks for your reply. How about add a parameter for invocation_directory() function, like invocation_directory(isNative), the default value for isNative is false, if we call it by invocation_directory(true) will get the native path?

BTW:

> Given the benefit of hindsight, maybe doing this translation isn't a good idea, since it's very confusing, but changing it now might not be a good idea for backwards-compatibility.

In the long term，remove the translation is still a good choice before the v1.0 version, IMO.

**Comment by casey** [comment]
Whoops! I accidentally edited your comment instead of replying. I tried to revert my edit. Here's my reply:

> Thanks for your reply. How about add a parameter for `invocation_directory()` function, like `invocation_directory(isNative)`, the default value for `isNative` is `false`, if we call it by `invocation_directory(true)` will get the native path?

Currently, `just` doesn't have booleans, and adding an argument would break users of the old zero-argument function.

> In the long term，remove the translation is still a good choice before the `v1.0` version, IMO.

I agree, although I'd have to think about it. People do use cywin userlands, and so this might break other users.

**Comment by hustcer** [comment]
When I call `absolute_path` got an error, not sure if this is a bug? :
```
$> just --evaluate

error: Call to unknown function `absolute_path`
   |
32 | just_invoke := absolute_path(invocation_directory())
   |                ^^^^^^^^^^^^^                          
```

**Comment by casey** [comment]
> When I call `absolute_path` got an error, not sure if this is a bug? :

The `absolute_path()` and `error()` functions were just added, so they weren't in the version of `just` you were using. I just published 1.1.0 which includes both functions.

**Comment by mihaigalos** [comment]
How are variables treated?
I would expect them to be set once upon initialization but seems they're reinited on each `just` reinvocation from inside the `justfile`:
```justfile
set shell := ["bash", "-uc"]
JUST_INVOKE_DIR := invocation_directory()

test_invocation:
    #!/bin/bash
    echo {{ JUST_INVOKE_DIR }}
    just test_invocation2

test_invocation2:
    #!/bin/bash
    echo {{ JUST_INVOKE_DIR }}
```
This works the 1st time but seems incorrect the 2nd time around:
```bash
/tmp » just --justfile ~/git/pass/Justfile test_invocation
/tmp
/home/mihai/git/pass
```

**Comment by mihaigalos** [comment]
Anyway, in this specific case, even if the vars are reinited, shouldn't `invocation_directory()` propagate the current directory on each subsequent `just` invocation?

**Comment by casey** [comment]
@mihaigalos When `just` reinvokes itself, it's a completely new process with no knowledge of the parent process, so `invocation_directory()` will be the new invocation directory.

**Comment by hustcer** [comment]
Any update on this issue?  Is there anyway to get the correct path of just invoke directory on Windows?

**Comment by casey** [comment]
Hmmm, how about this:

```
export JUST_INVOKE_DIR := env_var_or_default("JUST_INVOKE_DIR", invocation_directory());
```

**Comment by hustcer** [comment]
@casey I mean the original issue described here: https://github.com/casey/just/issues/984#issue-1013494964
`JUST_INVOKE_DIR := invocation_directory()` will be evaluated as `"/d/Data/iWork/termix-nu"` on Windows, I have just tried yesterday

**Comment by casey** [comment]
Ah, sorry, I was reading recent comments, not the OP. No, unfortunately there still isn't a workaround.

What do you think of `invocation_directory_native()`, which would return the unmodified invocation directory?

**Comment by hustcer** [comment]
That's fine for me. Thanks

**Comment by casey** [comment]
Added in #1507!
