### ISSUE TITLE
Machine readable metadata from justfile?

### ISSUE THREAD

**Issue by dionjwa** [casey/just#989]
I'm exploring showing visual depictions of dependencies as a means of automated documentation.

Idea:

just -f justfile --metadata | `<custom script>` | mermaid live image/link

Where the link goes to e.g. https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4gICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

(the graph content is baked into the URL and is a simple DSL)

What I would need is a machine readable (JSON preferably) description of a justfile, something like:

```json
{
    "commands": [
        {
            "command": "do_stuff",
            "docstring": "this is the docstring"
        },
        {
            "command": "do_stuff_but_more",
            "docstring": "this is the docstring",
            "dependencies": [
                {
                    "command": "do_stuff",
                    "args": []
                }
            ]
        }
    ]
}
```

That would open the door to other downstream/upstream tools being able to automatically understand `justfiles`.

Happy to elaborate more if this doesn't make sense. Basically, allow outputting the data structure right after parsing.

**Comment by casey** [comment]
This is actually something I've wanted to do for a while, but there hasn't been a motivating use case.

There was one in #638, but that turned out not to need the full contents of the justfile. I closed #638 in favor of this issue, because that one has a bunch of outdated discussion.

I started working on this in #992. It adds a `--json` subcommand that outputs the parsed justfile as JSON. (I'm actually thinking of adding a `--format=json` argument to `--dump` instead of adding a new subcommand, since eventually people might want formats other than JSON)

It doesn't do anything useful yet, but as I work on it more I'll ping you to make sure the output is what you had in mind.

**Comment by dionjwa** [comment]
Awesome thank you!!

**Comment by wearpants** [comment]
@dionjwa  is the script you used to generate visualization available / would you be willing to share it? I have the same need, and bad RSI right now, trying to avoid re-implementing if possible

**Comment by snoblenet** [comment]
For now you can do something like `cat justfile | jc --ini | jq`
